// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/organization/v1/service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/linzhengen/hub/server/pb/hub/annotations/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrganizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Lowercase letters, digits and hyphens. It travels in URLs and identifiers,
	// so anything that would have to be escaped somewhere is refused here.
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	// PLATFORM is refused: there is one, and migration 000002 created it.
	Kind          OrganizationKind `protobuf:"varint,3,opt,name=kind,proto3,enum=system.organization.v1.OrganizationKind" json:"kind,omitempty"`
	Description   string           `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_system_organization_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateOrganizationRequest) GetKind() OrganizationKind {
	if x != nil {
		return x.Kind
	}
	return OrganizationKind_ORGANIZATION_KIND_UNSPECIFIED
}

func (x *CreateOrganizationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResponse) Reset() {
	*x = CreateOrganizationResponse{}
	mi := &file_system_organization_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResponse) ProtoMessage() {}

func (x *CreateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type GetOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_system_organization_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationResponse) Reset() {
	*x = GetOrganizationResponse{}
	mi := &file_system_organization_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationResponse) ProtoMessage() {}

func (x *GetOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrganizationResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type ListOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Kind          OrganizationKind       `protobuf:"varint,3,opt,name=kind,proto3,enum=system.organization.v1.OrganizationKind" json:"kind,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationRequest) Reset() {
	*x = ListOrganizationRequest{}
	mi := &file_system_organization_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationRequest) ProtoMessage() {}

func (x *ListOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListOrganizationRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ListOrganizationRequest) GetKind() OrganizationKind {
	if x != nil {
		return x.Kind
	}
	return OrganizationKind_ORGANIZATION_KIND_UNSPECIFIED
}

func (x *ListOrganizationRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrganizationRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*Organization        `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationResponse) Reset() {
	*x = ListOrganizationResponse{}
	mi := &file_system_organization_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationResponse) ProtoMessage() {}

func (x *ListOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrganizationResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        OrganizationStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=system.organization.v1.OrganizationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_system_organization_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetStatus() OrganizationStatus {
	if x != nil {
		return x.Status
	}
	return OrganizationStatus_ORGANIZATION_STATUS_UNSPECIFIED
}

type UpdateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationResponse) Reset() {
	*x = UpdateOrganizationResponse{}
	mi := &file_system_organization_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationResponse) ProtoMessage() {}

func (x *UpdateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrganizationResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type DeleteOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationRequest) Reset() {
	*x = DeleteOrganizationRequest{}
	mi := &file_system_organization_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationRequest) ProtoMessage() {}

func (x *DeleteOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationResponse) Reset() {
	*x = DeleteOrganizationResponse{}
	mi := &file_system_organization_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationResponse) ProtoMessage() {}

func (x *DeleteOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{9}
}

type ListMyOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrganizationsRequest) Reset() {
	*x = ListMyOrganizationsRequest{}
	mi := &file_system_organization_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrganizationsRequest) ProtoMessage() {}

func (x *ListMyOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListMyOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{10}
}

type ListMyOrganizationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*Organization        `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrganizationsResponse) Reset() {
	*x = ListMyOrganizationsResponse{}
	mi := &file_system_organization_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrganizationsResponse) ProtoMessage() {}

func (x *ListMyOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_organization_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListMyOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_system_organization_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListMyOrganizationsResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

var File_system_organization_v1_service_proto protoreflect.FileDescriptor

const file_system_organization_v1_service_proto_rawDesc = "" +
	"\n" +
	"$system/organization/v1/service.proto\x12\x16system.organization.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a$hub/annotations/v1/annotations.proto\x1a\"system/organization/v1/model.proto\"\xf0\x01\n" +
	"\x19CreateOrganizationRequest\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12;\n" +
	"\x04slug\x18\x02 \x01(\tB'\xbaH$r\"\x10\x03\x18@2\x1c^[a-z0-9][a-z0-9-]*[a-z0-9]$R\x04slug\x12J\n" +
	"\x04kind\x18\x03 \x01(\x0e2(.system.organization.v1.OrganizationKindB\f\xbaH\t\x82\x01\x06\x10\x01 \x00 \x01R\x04kind\x12*\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bR\vdescription\"f\n" +
	"\x1aCreateOrganizationResponse\x12H\n" +
	"\forganization\x18\x01 \x01(\v2$.system.organization.v1.OrganizationR\forganization\"2\n" +
	"\x16GetOrganizationRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"c\n" +
	"\x17GetOrganizationResponse\x12H\n" +
	"\forganization\x18\x01 \x01(\v2$.system.organization.v1.OrganizationR\forganization\"\xd4\x01\n" +
	"\x17ListOrganizationRequest\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x04name\x12\x1b\n" +
	"\x04slug\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@R\x04slug\x12F\n" +
	"\x04kind\x18\x03 \x01(\x0e2(.system.organization.v1.OrganizationKindB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04kind\x12\x1e\n" +
	"\x05limit\x18\x04 \x01(\rB\b\xbaH\x05*\x03\x18\xc8\x01R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\rR\x06offset\"|\n" +
	"\x18ListOrganizationResponse\x12J\n" +
	"\rorganizations\x18\x01 \x03(\v2$.system.organization.v1.OrganizationR\rorganizations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x8e\x02\n" +
	"\x19UpdateOrganizationRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12;\n" +
	"\x04slug\x18\x03 \x01(\tB'\xbaH$r\"\x10\x03\x18@2\x1c^[a-z0-9][a-z0-9-]*[a-z0-9]$R\x04slug\x12*\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bR\vdescription\x12N\n" +
	"\x06status\x18\x05 \x01(\x0e2*.system.organization.v1.OrganizationStatusB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06status\"f\n" +
	"\x1aUpdateOrganizationResponse\x12H\n" +
	"\forganization\x18\x01 \x01(\v2$.system.organization.v1.OrganizationR\forganization\"5\n" +
	"\x19DeleteOrganizationRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x1c\n" +
	"\x1aDeleteOrganizationResponse\"\x1c\n" +
	"\x1aListMyOrganizationsRequest\"i\n" +
	"\x1bListMyOrganizationsResponse\x12J\n" +
	"\rorganizations\x18\x01 \x03(\v2$.system.organization.v1.OrganizationR\rorganizations2\xfe\n" +
	"\n" +
	"\x13OrganizationService\x12\xf2\x01\n" +
	"\x12CreateOrganization\x121.system.organization.v1.CreateOrganizationRequest\x1a2.system.organization.v1.CreateOrganizationResponse\"u\x8a\xa6\x1dQ\"OCreate an organization: a boundary that groups and permissions are held within.\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/organizations\x12\xbc\x01\n" +
	"\x0fGetOrganization\x12..system.organization.v1.GetOrganizationRequest\x1a/.system.organization.v1.GetOrganizationResponse\"H\x8a\xa6\x1d\"\" Get a single organization by id.\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/organizations/{id}\x12\xd8\x01\n" +
	"\x10ListOrganization\x12/.system.organization.v1.ListOrganizationRequest\x1a0.system.organization.v1.ListOrganizationResponse\"a\x8a\xa6\x1d@\">List organizations, optionally narrowed by name, slug or kind.\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/organizations\x12\xf0\x01\n" +
	"\x12UpdateOrganization\x121.system.organization.v1.UpdateOrganizationRequest\x1a2.system.organization.v1.UpdateOrganizationResponse\"s\x8a\xa6\x1dJ\"HRename an organization or change its status. The kind cannot be changed.\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/api/v1/organizations/{id}\x12\x80\x02\n" +
	"\x12DeleteOrganization\x121.system.organization.v1.DeleteOrganizationRequest\x1a2.system.organization.v1.DeleteOrganizationResponse\"\x82\x01\x8a\xa6\x1d\\\"ZDelete an organization and every group in it. The platform organization cannot be deleted.\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v1/organizations/{id}\x12\xe1\x01\n" +
	"\x13ListMyOrganizations\x122.system.organization.v1.ListMyOrganizationsRequest\x1a3.system.organization.v1.ListMyOrganizationsResponse\"a\x8a\xa6\x1d=\b\x01\"9List the organizations the authenticated user belongs to.\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/me/organizationsB<Z:github.com/linzhengen/hub/server/pb/system/organization/v1b\x06proto3"

var (
	file_system_organization_v1_service_proto_rawDescOnce sync.Once
	file_system_organization_v1_service_proto_rawDescData []byte
)

func file_system_organization_v1_service_proto_rawDescGZIP() []byte {
	file_system_organization_v1_service_proto_rawDescOnce.Do(func() {
		file_system_organization_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_organization_v1_service_proto_rawDesc), len(file_system_organization_v1_service_proto_rawDesc)))
	})
	return file_system_organization_v1_service_proto_rawDescData
}

var file_system_organization_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_system_organization_v1_service_proto_goTypes = []any{
	(*CreateOrganizationRequest)(nil),   // 0: system.organization.v1.CreateOrganizationRequest
	(*CreateOrganizationResponse)(nil),  // 1: system.organization.v1.CreateOrganizationResponse
	(*GetOrganizationRequest)(nil),      // 2: system.organization.v1.GetOrganizationRequest
	(*GetOrganizationResponse)(nil),     // 3: system.organization.v1.GetOrganizationResponse
	(*ListOrganizationRequest)(nil),     // 4: system.organization.v1.ListOrganizationRequest
	(*ListOrganizationResponse)(nil),    // 5: system.organization.v1.ListOrganizationResponse
	(*UpdateOrganizationRequest)(nil),   // 6: system.organization.v1.UpdateOrganizationRequest
	(*UpdateOrganizationResponse)(nil),  // 7: system.organization.v1.UpdateOrganizationResponse
	(*DeleteOrganizationRequest)(nil),   // 8: system.organization.v1.DeleteOrganizationRequest
	(*DeleteOrganizationResponse)(nil),  // 9: system.organization.v1.DeleteOrganizationResponse
	(*ListMyOrganizationsRequest)(nil),  // 10: system.organization.v1.ListMyOrganizationsRequest
	(*ListMyOrganizationsResponse)(nil), // 11: system.organization.v1.ListMyOrganizationsResponse
	(OrganizationKind)(0),               // 12: system.organization.v1.OrganizationKind
	(*Organization)(nil),                // 13: system.organization.v1.Organization
	(OrganizationStatus)(0),             // 14: system.organization.v1.OrganizationStatus
}
var file_system_organization_v1_service_proto_depIdxs = []int32{
	12, // 0: system.organization.v1.CreateOrganizationRequest.kind:type_name -> system.organization.v1.OrganizationKind
	13, // 1: system.organization.v1.CreateOrganizationResponse.organization:type_name -> system.organization.v1.Organization
	13, // 2: system.organization.v1.GetOrganizationResponse.organization:type_name -> system.organization.v1.Organization
	12, // 3: system.organization.v1.ListOrganizationRequest.kind:type_name -> system.organization.v1.OrganizationKind
	13, // 4: system.organization.v1.ListOrganizationResponse.organizations:type_name -> system.organization.v1.Organization
	14, // 5: system.organization.v1.UpdateOrganizationRequest.status:type_name -> system.organization.v1.OrganizationStatus
	13, // 6: system.organization.v1.UpdateOrganizationResponse.organization:type_name -> system.organization.v1.Organization
	13, // 7: system.organization.v1.ListMyOrganizationsResponse.organizations:type_name -> system.organization.v1.Organization
	0,  // 8: system.organization.v1.OrganizationService.CreateOrganization:input_type -> system.organization.v1.CreateOrganizationRequest
	2,  // 9: system.organization.v1.OrganizationService.GetOrganization:input_type -> system.organization.v1.GetOrganizationRequest
	4,  // 10: system.organization.v1.OrganizationService.ListOrganization:input_type -> system.organization.v1.ListOrganizationRequest
	6,  // 11: system.organization.v1.OrganizationService.UpdateOrganization:input_type -> system.organization.v1.UpdateOrganizationRequest
	8,  // 12: system.organization.v1.OrganizationService.DeleteOrganization:input_type -> system.organization.v1.DeleteOrganizationRequest
	10, // 13: system.organization.v1.OrganizationService.ListMyOrganizations:input_type -> system.organization.v1.ListMyOrganizationsRequest
	1,  // 14: system.organization.v1.OrganizationService.CreateOrganization:output_type -> system.organization.v1.CreateOrganizationResponse
	3,  // 15: system.organization.v1.OrganizationService.GetOrganization:output_type -> system.organization.v1.GetOrganizationResponse
	5,  // 16: system.organization.v1.OrganizationService.ListOrganization:output_type -> system.organization.v1.ListOrganizationResponse
	7,  // 17: system.organization.v1.OrganizationService.UpdateOrganization:output_type -> system.organization.v1.UpdateOrganizationResponse
	9,  // 18: system.organization.v1.OrganizationService.DeleteOrganization:output_type -> system.organization.v1.DeleteOrganizationResponse
	11, // 19: system.organization.v1.OrganizationService.ListMyOrganizations:output_type -> system.organization.v1.ListMyOrganizationsResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_system_organization_v1_service_proto_init() }
func file_system_organization_v1_service_proto_init() {
	if File_system_organization_v1_service_proto != nil {
		return
	}
	file_system_organization_v1_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_organization_v1_service_proto_rawDesc), len(file_system_organization_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_organization_v1_service_proto_goTypes,
		DependencyIndexes: file_system_organization_v1_service_proto_depIdxs,
		MessageInfos:      file_system_organization_v1_service_proto_msgTypes,
	}.Build()
	File_system_organization_v1_service_proto = out.File
	file_system_organization_v1_service_proto_goTypes = nil
	file_system_organization_v1_service_proto_depIdxs = nil
}
