// Code generated by gen-adapter. DO NOT EDIT.
package persistence

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	postgressqlc "github.com/linzhengen/hub/server/internal/infrastructure/persistence/postgres/sqlc"
	"github.com/sqlc-dev/pqtype"
)

// AccessRequestModel represents a AccessRequest in the database
type AccessRequestModel struct {
	ID              string
	RequesterUserID string
	SubjectUserID   string
	GroupID         string
	Reason          string
	RequestedUntil  sql.NullTime
	Status          string
	Origin          string
	SessionID       string
	DecidedByUserID string
	DecidedAt       sql.NullTime
	DecisionComment string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// AgentModel represents a Agent in the database
type AgentModel struct {
	ID              string
	OrgID           string
	UserID          string
	Name            string
	Description     string
	ClientID        string
	KeycloakID      string
	AuthMethod      string
	SecretRotatedAt time.Time
	ParentAgentID   string
	CreatedByUserID string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// AuditLogModel represents a AuditLog in the database
type AuditLogModel struct {
	ID          string
	ActorUserID string
	OrgID       string
	Channel     string
	AiSessionID string
	Resource    string
	Action      string
	TargetID    string
	Arguments   json.RawMessage
	Succeeded   bool
	Error       string
	Client      string
	CreatedAt   time.Time
	ApprovalID  string
}

// ChatMessageModel represents a ChatMessage in the database
type ChatMessageModel struct {
	ID        string
	SessionID string
	Role      string
	Content   string
	CreatedAt time.Time
}

// ChatSessionModel represents a ChatSession in the database
type ChatSessionModel struct {
	ID         string
	UserID     string
	Title      string
	CreatedAt  time.Time
	TokensUsed int64
}

// ChatToolProposalModel represents a ChatToolProposal in the database
type ChatToolProposalModel struct {
	ID           string
	SessionID    string
	ToolName     string
	Arguments    json.RawMessage
	Continuation []byte
	Status       string
	CreatedAt    time.Time
	DecidedAt    sql.NullTime
}

// GroupModel represents a Group in the database
type GroupModel struct {
	ID          string
	Name        string
	Description string
	Status      string
	OrgID       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// GroupRoleModel represents a GroupRole in the database
type GroupRoleModel struct {
	GroupID   string
	RoleID    string
	ExpiresAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

// OrganizationModel represents a Organization in the database
type OrganizationModel struct {
	ID          string
	Name        string
	Slug        string
	Kind        string
	Description string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// PermissionModel represents a Permission in the database
type PermissionModel struct {
	ID          string
	Verb        string
	ResourceID  string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// RbacRevisionModel represents a RbacRevision in the database
type RbacRevisionModel struct {
	ID        int16
	Revision  int64
	UpdatedAt time.Time
}

// ResourceModel represents a Resource in the database
type ResourceModel struct {
	ID           string
	ParentID     string
	Name         string
	Identifier   string
	Type         string
	Path         string
	Component    string
	DisplayOrder int32
	Description  string
	Metadata     map[string]string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// RoleModel represents a Role in the database
type RoleModel struct {
	ID          string
	Name        string
	Description string
	OrgID       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// RolePermissionModel represents a RolePermission in the database
type RolePermissionModel struct {
	RoleID       string
	PermissionID string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// SelectAccessPathsModel represents a SelectAccessPaths in the database
type SelectAccessPathsModel struct {
	GroupID      string
	GroupName    string
	RoleID       string
	RoleName     string
	PermissionID string
	Identifier   string
	Verb         string
	ExpiresAt    sql.NullTime
	OrgID        string
	OrgName      string
	OrgKind      string
}

// SelectMembershipsModel represents a SelectMemberships in the database
type SelectMembershipsModel struct {
	ID        string
	Username  string
	GroupID   string
	ExpiresAt sql.NullTime
}

// SelectUserAccessPathsModel represents a SelectUserAccessPaths in the database
type SelectUserAccessPathsModel struct {
	GroupID        string
	GroupName      string
	RoleID         string
	RoleName       string
	PermissionID   string
	Identifier     string
	Verb           string
	GroupExpiresAt sql.NullTime
	RoleExpiresAt  sql.NullTime
	OrgID          string
	OrgName        string
	OrgKind        string
}

// SelectUserAuthorizedPolicesModel represents a SelectUserAuthorizedPolices in the database
type SelectUserAuthorizedPolicesModel struct {
	ID             string
	Identifier     string
	Verb           string
	GroupExpiresAt sql.NullTime
	RoleExpiresAt  sql.NullTime
	OrgID          string
	OrgKind        string
}

// ServiceAccountModel represents a ServiceAccount in the database
type ServiceAccountModel struct {
	ID              string
	UserID          string
	Name            string
	Description     string
	ClientID        string
	KeycloakID      string
	CreatedByUserID string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// UserModel represents a User in the database
type UserModel struct {
	ID        string
	Username  string
	Email     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// UserGroupModel represents a UserGroup in the database
type UserGroupModel struct {
	UserID    string
	GroupID   string
	ExpiresAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Querier is a common interface for database operations
type Querier interface {
	WithTx(tx *sql.Tx) Querier

	AddChatSessionTokens(ctx context.Context, ID string, TokensUsed int64) error
	AddPermissionToRole(ctx context.Context, RoleID string, PermissionID string) error
	CountAccessRequests(ctx context.Context, RequesterUserID string, SubjectUserID string, GroupID string, Status string, OrgIds []string) (int64, error)
	CountAgentChildren(ctx context.Context, parentAgentID string) (int64, error)
	CountAgents(ctx context.Context, OrgID string, ParentAgentID string, OrgIds []string) (int64, error)
	CountServiceAccounts(ctx context.Context) (int64, error)
	CreateAccessRequest(ctx context.Context, ID string, RequesterUserID string, SubjectUserID string, GroupID string, Reason string, RequestedUntil sql.NullTime, Status string, Origin string, SessionID string) error
	CreateAgent(ctx context.Context, ID string, OrgID string, UserID string, Name string, Description string, ClientID string, KeycloakID string, AuthMethod string, ParentAgentID string, CreatedByUserID string) error
	CreateAuditLog(ctx context.Context, ActorUserID string, OrgID string, Channel string, AiSessionID string, Resource string, Action string, TargetID string, Arguments json.RawMessage, Succeeded bool, Error string, Client string, ApprovalID string) (*AuditLogModel, error)
	CreateChatMessage(ctx context.Context, SessionID string, Role string, Content string) (*ChatMessageModel, error)
	CreateChatSession(ctx context.Context, UserID string, Title string) (*ChatSessionModel, error)
	CreateChatToolProposal(ctx context.Context, SessionID string, ToolName string, Arguments json.RawMessage, Continuation []byte) (*ChatToolProposalModel, error)
	CreateGroup(ctx context.Context, ID string, Name string, Status string, Description string, OrgID string) error
	CreateGroupRole(ctx context.Context, GroupID string, RoleID string, ExpiresAt sql.NullTime) error
	CreateOrganization(ctx context.Context, ID string, Name string, Slug string, Kind string, Description string, Status string) error
	CreatePermission(ctx context.Context, ID string, Verb string, ResourceID string, Description string) error
	CreateResource(ctx context.Context, ID string, ParentID string, Name string, Identifier string, Type string, Path string, Component string, DisplayOrder int32, Description string, Metadata map[string]string, Status string) error
	CreateRole(ctx context.Context, ID string, Name string, Description string, OrgID string) error
	CreateServiceAccount(ctx context.Context, ID string, UserID string, Name string, Description string, ClientID string, KeycloakID string, CreatedByUserID string) error
	CreateUser(ctx context.Context, ID string, Username string, Email string, Status string) error
	CreateUserGroup(ctx context.Context, UserID string, GroupID string, ExpiresAt sql.NullTime) error
	DecideAccessRequest(ctx context.Context, Status string, DecidedByUserID string, DecidedAt sql.NullTime, DecisionComment string, ID string) (*AccessRequestModel, error)
	DecideChatToolProposal(ctx context.Context, ID string, Status string) (*ChatToolProposalModel, error)
	DeleteAgent(ctx context.Context, id string) error
	DeleteChatSession(ctx context.Context, ID string, UserID string) error
	DeleteGroup(ctx context.Context, id string) error
	DeleteGroupAllRole(ctx context.Context, groupID string) error
	DeleteGroupRole(ctx context.Context, GroupID string, RoleID string) error
	DeleteOrganization(ctx context.Context, id string) error
	DeletePermission(ctx context.Context, id string) error
	DeleteResource(ctx context.Context, id string) error
	DeleteRole(ctx context.Context, id string) error
	DeleteRoleAllPermission(ctx context.Context, roleID string) error
	DeleteServiceAccount(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserAllGroup(ctx context.Context, userID string) error
	DeleteUserGroup(ctx context.Context, UserID string, GroupID string) error
	IsPermissionInRole(ctx context.Context, RoleID string, PermissionID string) (bool, error)
	IsUserInGroup(ctx context.Context, UserID string, GroupID string) (bool, error)
	ListAccessRequests(ctx context.Context, RequesterUserID string, SubjectUserID string, GroupID string, Status string, OrgIds []string, RowOffset int32, RowLimit int32) ([]*AccessRequestModel, error)
	ListAgents(ctx context.Context, OrgID string, ParentAgentID string, OrgIds []string, RowOffset int32, RowLimit int32) ([]*AgentModel, error)
	ListServiceAccounts(ctx context.Context, RowOffset int32, RowLimit int32) ([]*ServiceAccountModel, error)
	RecordAgentSecretRotation(ctx context.Context, id string) error
	RemoveAllUsersFromGroup(ctx context.Context, groupID string) error
	RemovePermissionFromRole(ctx context.Context, RoleID string, PermissionID string) error
	SelectAccessPath(ctx context.Context) ([]*SelectAccessPathsModel, error)
	SelectAccessRequest(ctx context.Context, id string) (*AccessRequestModel, error)
	SelectAgent(ctx context.Context, id string) (*AgentModel, error)
	SelectChatMessagesBySessionId(ctx context.Context, SessionID string, UserID string) ([]*ChatMessageModel, error)
	SelectChatSessionById(ctx context.Context, ID string, UserID string) (*ChatSessionModel, error)
	SelectChatSessionsByUserId(ctx context.Context, userID string) ([]*ChatSessionModel, error)
	SelectChatToolProposalById(ctx context.Context, ID string, UserID string) (*ChatToolProposalModel, error)
	SelectGroupById(ctx context.Context, id string) (*GroupModel, error)
	SelectGroupForUpdate(ctx context.Context, id string) (*GroupModel, error)
	SelectGroupRoleByGroupId(ctx context.Context, groupID string) ([]*GroupRoleModel, error)
	SelectMembership(ctx context.Context) ([]*SelectMembershipsModel, error)
	SelectOrganization(ctx context.Context, id string) (*OrganizationModel, error)
	SelectOrganizationBySlug(ctx context.Context, slug string) (*OrganizationModel, error)
	SelectPermissionById(ctx context.Context, id string) (*PermissionModel, error)
	SelectPermissionByResourceId(ctx context.Context, resourceID string) ([]*PermissionModel, error)
	SelectPermissionForUpdate(ctx context.Context, id string) (*PermissionModel, error)
	SelectRbacRevision(ctx context.Context) (int64, error)
	SelectResourceById(ctx context.Context, id string) (*ResourceModel, error)
	SelectResourceByIdentifier(ctx context.Context, identifier string) (*ResourceModel, error)
	SelectResourceForUpdate(ctx context.Context, id string) (*ResourceModel, error)
	SelectRoleById(ctx context.Context, id string) (*RoleModel, error)
	SelectRoleForUpdate(ctx context.Context, id string) (*RoleModel, error)
	SelectRolePermissionByRoleId(ctx context.Context, roleID string) ([]*RolePermissionModel, error)
	SelectServiceAccount(ctx context.Context, id string) (*ServiceAccountModel, error)
	SelectUserAccessPath(ctx context.Context, id string) ([]*SelectUserAccessPathsModel, error)
	SelectUserAuthorizedPolicies(ctx context.Context, id string) ([]*SelectUserAuthorizedPolicesModel, error)
	SelectUserById(ctx context.Context, id string) (*UserModel, error)
	SelectUserForUpdate(ctx context.Context, id string) (*UserModel, error)
	SelectUserGroupByGroupId(ctx context.Context, groupID string) ([]*UserGroupModel, error)
	SelectUserGroupByUserId(ctx context.Context, userID string) ([]*UserGroupModel, error)
	SelectUserOrganization(ctx context.Context, userID string) ([]*OrganizationModel, error)
	UpdateGroup(ctx context.Context, Name string, Description string, Status string, ID string) error
	UpdateOrganization(ctx context.Context, Name string, Slug string, Description string, Status string, ID string) error
	UpdatePermission(ctx context.Context, Verb string, ResourceID string, Description string, ID string) error
	UpdateResource(ctx context.Context, ParentID string, Name string, Identifier string, Type string, Path string, Component string, DisplayOrder int32, Description string, Metadata map[string]string, Status string, ID string) error
	UpdateRole(ctx context.Context, Name string, Description string, ID string) error
	UpdateUser(ctx context.Context, Username string, Email string, Status string, ID string) error
}

// PostgreSQLQuerier implements Querier for PostgreSQL
type PostgreSQLQuerier struct {
	q *postgressqlc.Queries
}

// NewPostgreSQLQuerier creates a new PostgreSQLQuerier
func NewPostgreSQLQuerier(q *postgressqlc.Queries) *PostgreSQLQuerier {
	return &PostgreSQLQuerier{q: q}
}

func (p *PostgreSQLQuerier) WithTx(tx *sql.Tx) Querier {
	return &PostgreSQLQuerier{q: p.q.WithTx(tx)}
}

func (p *PostgreSQLQuerier) AddChatSessionTokens(ctx context.Context, ID string, TokensUsed int64) error {
	return p.q.AddChatSessionTokens(ctx, postgressqlc.AddChatSessionTokensParams{
		ID:         ID,
		TokensUsed: TokensUsed,
	})

}

func (p *PostgreSQLQuerier) AddPermissionToRole(ctx context.Context, RoleID string, PermissionID string) error {
	return p.q.AddPermissionToRole(ctx, postgressqlc.AddPermissionToRoleParams{
		RoleID:       RoleID,
		PermissionID: PermissionID,
	})

}

func (p *PostgreSQLQuerier) CountAccessRequests(ctx context.Context, RequesterUserID string, SubjectUserID string, GroupID string, Status string, OrgIds []string) (int64, error) {
	row, err := p.q.CountAccessRequests(ctx, postgressqlc.CountAccessRequestsParams{
		RequesterUserID: sql.NullString{String: RequesterUserID, Valid: RequesterUserID != ""},
		SubjectUserID:   sql.NullString{String: SubjectUserID, Valid: SubjectUserID != ""},
		GroupID:         sql.NullString{String: GroupID, Valid: GroupID != ""},
		Status:          sql.NullString{String: Status, Valid: Status != ""},
		OrgIds:          OrgIds,
	})
	if err != nil {
		return 0, err
	}
	return row, nil

}

func (p *PostgreSQLQuerier) CountAgentChildren(ctx context.Context, parentAgentID string) (int64, error) {
	row, err := p.q.CountAgentChildren(ctx, parentAgentID)
	if err != nil {
		return 0, err
	}
	return row, nil

}

func (p *PostgreSQLQuerier) CountAgents(ctx context.Context, OrgID string, ParentAgentID string, OrgIds []string) (int64, error) {
	row, err := p.q.CountAgents(ctx, postgressqlc.CountAgentsParams{
		OrgID:         sql.NullString{String: OrgID, Valid: OrgID != ""},
		ParentAgentID: sql.NullString{String: ParentAgentID, Valid: ParentAgentID != ""},
		OrgIds:        OrgIds,
	})
	if err != nil {
		return 0, err
	}
	return row, nil

}

func (p *PostgreSQLQuerier) CountServiceAccounts(ctx context.Context) (int64, error) {
	row, err := p.q.CountServiceAccounts(ctx)
	if err != nil {
		return 0, err
	}
	return row, nil

}

func (p *PostgreSQLQuerier) CreateAccessRequest(ctx context.Context, ID string, RequesterUserID string, SubjectUserID string, GroupID string, Reason string, RequestedUntil sql.NullTime, Status string, Origin string, SessionID string) error {
	return p.q.CreateAccessRequest(ctx, postgressqlc.CreateAccessRequestParams{
		ID:              ID,
		RequesterUserID: RequesterUserID,
		SubjectUserID:   SubjectUserID,
		GroupID:         GroupID,
		Reason:          Reason,
		RequestedUntil:  RequestedUntil,
		Status:          Status,
		Origin:          Origin,
		SessionID:       sql.NullString{String: SessionID, Valid: SessionID != ""},
	})

}

func (p *PostgreSQLQuerier) CreateAgent(ctx context.Context, ID string, OrgID string, UserID string, Name string, Description string, ClientID string, KeycloakID string, AuthMethod string, ParentAgentID string, CreatedByUserID string) error {
	return p.q.CreateAgent(ctx, postgressqlc.CreateAgentParams{
		ID:              ID,
		OrgID:           OrgID,
		UserID:          UserID,
		Name:            Name,
		Description:     Description,
		ClientID:        ClientID,
		KeycloakID:      KeycloakID,
		AuthMethod:      AuthMethod,
		ParentAgentID:   sql.NullString{String: ParentAgentID, Valid: ParentAgentID != ""},
		CreatedByUserID: CreatedByUserID,
	})

}

func (p *PostgreSQLQuerier) CreateAuditLog(ctx context.Context, ActorUserID string, OrgID string, Channel string, AiSessionID string, Resource string, Action string, TargetID string, Arguments json.RawMessage, Succeeded bool, Error string, Client string, ApprovalID string) (*AuditLogModel, error) {
	row, err := p.q.CreateAuditLog(ctx, postgressqlc.CreateAuditLogParams{
		ActorUserID: ActorUserID,
		OrgID:       sql.NullString{String: OrgID, Valid: OrgID != ""},
		Channel:     Channel,
		AiSessionID: sql.NullString{String: AiSessionID, Valid: AiSessionID != ""},
		Resource:    Resource,
		Action:      Action,
		TargetID:    TargetID,
		Arguments:   Arguments,
		Succeeded:   Succeeded,
		Error:       Error,
		Client:      Client,
		ApprovalID:  sql.NullString{String: ApprovalID, Valid: ApprovalID != ""},
	})
	if err != nil {
		return nil, err
	}
	return &AuditLogModel{
		ID:          row.ID,
		ActorUserID: row.ActorUserID,
		OrgID:       row.OrgID.String,
		Channel:     row.Channel,
		AiSessionID: row.AiSessionID.String,
		Resource:    row.Resource,
		Action:      row.Action,
		TargetID:    row.TargetID,
		Arguments:   row.Arguments,
		Succeeded:   row.Succeeded,
		Error:       row.Error,
		Client:      row.Client,
		CreatedAt:   row.CreatedAt,
		ApprovalID:  row.ApprovalID.String,
	}, nil

}

func (p *PostgreSQLQuerier) CreateChatMessage(ctx context.Context, SessionID string, Role string, Content string) (*ChatMessageModel, error) {
	row, err := p.q.CreateChatMessage(ctx, postgressqlc.CreateChatMessageParams{
		SessionID: SessionID,
		Role:      Role,
		Content:   Content,
	})
	if err != nil {
		return nil, err
	}
	return &ChatMessageModel{
		ID:        row.ID,
		SessionID: row.SessionID,
		Role:      row.Role,
		Content:   row.Content,
		CreatedAt: row.CreatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) CreateChatSession(ctx context.Context, UserID string, Title string) (*ChatSessionModel, error) {
	row, err := p.q.CreateChatSession(ctx, postgressqlc.CreateChatSessionParams{
		UserID: UserID,
		Title:  Title,
	})
	if err != nil {
		return nil, err
	}
	return &ChatSessionModel{
		ID:         row.ID,
		UserID:     row.UserID,
		Title:      row.Title,
		CreatedAt:  row.CreatedAt,
		TokensUsed: row.TokensUsed,
	}, nil

}

func (p *PostgreSQLQuerier) CreateChatToolProposal(ctx context.Context, SessionID string, ToolName string, Arguments json.RawMessage, Continuation []byte) (*ChatToolProposalModel, error) {
	row, err := p.q.CreateChatToolProposal(ctx, postgressqlc.CreateChatToolProposalParams{
		SessionID:    SessionID,
		ToolName:     ToolName,
		Arguments:    Arguments,
		Continuation: Continuation,
	})
	if err != nil {
		return nil, err
	}
	return &ChatToolProposalModel{
		ID:           row.ID,
		SessionID:    row.SessionID,
		ToolName:     row.ToolName,
		Arguments:    row.Arguments,
		Continuation: row.Continuation,
		Status:       row.Status,
		CreatedAt:    row.CreatedAt,
		DecidedAt:    row.DecidedAt,
	}, nil

}

func (p *PostgreSQLQuerier) CreateGroup(ctx context.Context, ID string, Name string, Status string, Description string, OrgID string) error {
	return p.q.CreateGroup(ctx, postgressqlc.CreateGroupParams{
		ID:          ID,
		Name:        Name,
		Status:      Status,
		Description: Description,
		OrgID:       OrgID,
	})

}

func (p *PostgreSQLQuerier) CreateGroupRole(ctx context.Context, GroupID string, RoleID string, ExpiresAt sql.NullTime) error {
	return p.q.CreateGroupRole(ctx, postgressqlc.CreateGroupRoleParams{
		GroupID:   GroupID,
		RoleID:    RoleID,
		ExpiresAt: ExpiresAt,
	})

}

func (p *PostgreSQLQuerier) CreateOrganization(ctx context.Context, ID string, Name string, Slug string, Kind string, Description string, Status string) error {
	return p.q.CreateOrganization(ctx, postgressqlc.CreateOrganizationParams{
		ID:          ID,
		Name:        Name,
		Slug:        Slug,
		Kind:        Kind,
		Description: Description,
		Status:      Status,
	})

}

func (p *PostgreSQLQuerier) CreatePermission(ctx context.Context, ID string, Verb string, ResourceID string, Description string) error {
	return p.q.CreatePermission(ctx, postgressqlc.CreatePermissionParams{
		ID:          ID,
		Verb:        Verb,
		ResourceID:  ResourceID,
		Description: Description,
	})

}

func (p *PostgreSQLQuerier) CreateResource(ctx context.Context, ID string, ParentID string, Name string, Identifier string, Type string, Path string, Component string, DisplayOrder int32, Description string, Metadata map[string]string, Status string) error {
	m, _ := json.Marshal(Metadata)
	return p.q.CreateResource(ctx, postgressqlc.CreateResourceParams{
		ID:           ID,
		ParentID:     sql.NullString{String: ParentID, Valid: ParentID != ""},
		Name:         Name,
		Identifier:   Identifier,
		Type:         Type,
		Path:         sql.NullString{String: Path, Valid: Path != ""},
		Component:    sql.NullString{String: Component, Valid: Component != ""},
		DisplayOrder: sql.NullInt32{Int32: DisplayOrder, Valid: true},
		Description:  Description,
		Metadata:     pqtype.NullRawMessage{RawMessage: m, Valid: m != nil},
		Status:       Status,
	})

}

func (p *PostgreSQLQuerier) CreateRole(ctx context.Context, ID string, Name string, Description string, OrgID string) error {
	return p.q.CreateRole(ctx, postgressqlc.CreateRoleParams{
		ID:          ID,
		Name:        Name,
		Description: Description,
		OrgID:       sql.NullString{String: OrgID, Valid: OrgID != ""},
	})

}

func (p *PostgreSQLQuerier) CreateServiceAccount(ctx context.Context, ID string, UserID string, Name string, Description string, ClientID string, KeycloakID string, CreatedByUserID string) error {
	return p.q.CreateServiceAccount(ctx, postgressqlc.CreateServiceAccountParams{
		ID:              ID,
		UserID:          UserID,
		Name:            Name,
		Description:     Description,
		ClientID:        ClientID,
		KeycloakID:      KeycloakID,
		CreatedByUserID: CreatedByUserID,
	})

}

func (p *PostgreSQLQuerier) CreateUser(ctx context.Context, ID string, Username string, Email string, Status string) error {
	return p.q.CreateUser(ctx, postgressqlc.CreateUserParams{
		ID:       ID,
		Username: Username,
		Email:    Email,
		Status:   Status,
	})

}

func (p *PostgreSQLQuerier) CreateUserGroup(ctx context.Context, UserID string, GroupID string, ExpiresAt sql.NullTime) error {
	return p.q.CreateUserGroup(ctx, postgressqlc.CreateUserGroupParams{
		UserID:    UserID,
		GroupID:   GroupID,
		ExpiresAt: ExpiresAt,
	})

}

func (p *PostgreSQLQuerier) DecideAccessRequest(ctx context.Context, Status string, DecidedByUserID string, DecidedAt sql.NullTime, DecisionComment string, ID string) (*AccessRequestModel, error) {
	row, err := p.q.DecideAccessRequest(ctx, postgressqlc.DecideAccessRequestParams{
		Status:          Status,
		DecidedByUserID: sql.NullString{String: DecidedByUserID, Valid: DecidedByUserID != ""},
		DecidedAt:       DecidedAt,
		DecisionComment: DecisionComment,
		ID:              ID,
	})
	if err != nil {
		return nil, err
	}
	return &AccessRequestModel{
		ID:              row.ID,
		RequesterUserID: row.RequesterUserID,
		SubjectUserID:   row.SubjectUserID,
		GroupID:         row.GroupID,
		Reason:          row.Reason,
		RequestedUntil:  row.RequestedUntil,
		Status:          row.Status,
		Origin:          row.Origin,
		SessionID:       row.SessionID.String,
		DecidedByUserID: row.DecidedByUserID.String,
		DecidedAt:       row.DecidedAt,
		DecisionComment: row.DecisionComment,
		CreatedAt:       row.CreatedAt,
		UpdatedAt:       row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) DecideChatToolProposal(ctx context.Context, ID string, Status string) (*ChatToolProposalModel, error) {
	row, err := p.q.DecideChatToolProposal(ctx, postgressqlc.DecideChatToolProposalParams{
		ID:     ID,
		Status: Status,
	})
	if err != nil {
		return nil, err
	}
	return &ChatToolProposalModel{
		ID:           row.ID,
		SessionID:    row.SessionID,
		ToolName:     row.ToolName,
		Arguments:    row.Arguments,
		Continuation: row.Continuation,
		Status:       row.Status,
		CreatedAt:    row.CreatedAt,
		DecidedAt:    row.DecidedAt,
	}, nil

}

func (p *PostgreSQLQuerier) DeleteAgent(ctx context.Context, id string) error {
	return p.q.DeleteAgent(ctx, id)

}

func (p *PostgreSQLQuerier) DeleteChatSession(ctx context.Context, ID string, UserID string) error {
	return p.q.DeleteChatSession(ctx, postgressqlc.DeleteChatSessionParams{
		ID:     ID,
		UserID: UserID,
	})

}

func (p *PostgreSQLQuerier) DeleteGroup(ctx context.Context, id string) error {
	return p.q.DeleteGroup(ctx, id)

}

func (p *PostgreSQLQuerier) DeleteGroupAllRole(ctx context.Context, groupID string) error {
	return p.q.DeleteGroupAllRole(ctx, groupID)

}

func (p *PostgreSQLQuerier) DeleteGroupRole(ctx context.Context, GroupID string, RoleID string) error {
	return p.q.DeleteGroupRole(ctx, postgressqlc.DeleteGroupRoleParams{
		GroupID: GroupID,
		RoleID:  RoleID,
	})

}

func (p *PostgreSQLQuerier) DeleteOrganization(ctx context.Context, id string) error {
	return p.q.DeleteOrganization(ctx, id)

}

func (p *PostgreSQLQuerier) DeletePermission(ctx context.Context, id string) error {
	return p.q.DeletePermissions(ctx, id)

}

func (p *PostgreSQLQuerier) DeleteResource(ctx context.Context, id string) error {
	return p.q.DeleteResource(ctx, id)

}

func (p *PostgreSQLQuerier) DeleteRole(ctx context.Context, id string) error {
	return p.q.DeleteRole(ctx, id)

}

func (p *PostgreSQLQuerier) DeleteRoleAllPermission(ctx context.Context, roleID string) error {
	return p.q.DeleteRoleAllPermission(ctx, roleID)

}

func (p *PostgreSQLQuerier) DeleteServiceAccount(ctx context.Context, id string) error {
	return p.q.DeleteServiceAccount(ctx, id)

}

func (p *PostgreSQLQuerier) DeleteUser(ctx context.Context, id string) error {
	return p.q.DeleteUser(ctx, id)

}

func (p *PostgreSQLQuerier) DeleteUserAllGroup(ctx context.Context, userID string) error {
	return p.q.DeleteUserAllGroup(ctx, userID)

}

func (p *PostgreSQLQuerier) DeleteUserGroup(ctx context.Context, UserID string, GroupID string) error {
	return p.q.DeleteUserGroup(ctx, postgressqlc.DeleteUserGroupParams{
		UserID:  UserID,
		GroupID: GroupID,
	})

}

func (p *PostgreSQLQuerier) IsPermissionInRole(ctx context.Context, RoleID string, PermissionID string) (bool, error) {
	row, err := p.q.IsPermissionInRole(ctx, postgressqlc.IsPermissionInRoleParams{
		RoleID:       RoleID,
		PermissionID: PermissionID,
	})
	if err != nil {
		return false, err
	}
	return row, nil

}

func (p *PostgreSQLQuerier) IsUserInGroup(ctx context.Context, UserID string, GroupID string) (bool, error) {
	row, err := p.q.IsUserInGroup(ctx, postgressqlc.IsUserInGroupParams{
		UserID:  UserID,
		GroupID: GroupID,
	})
	if err != nil {
		return false, err
	}
	return row, nil

}

func (p *PostgreSQLQuerier) ListAccessRequests(ctx context.Context, RequesterUserID string, SubjectUserID string, GroupID string, Status string, OrgIds []string, RowOffset int32, RowLimit int32) ([]*AccessRequestModel, error) {
	rows, err := p.q.ListAccessRequests(ctx, postgressqlc.ListAccessRequestsParams{
		RequesterUserID: sql.NullString{String: RequesterUserID, Valid: RequesterUserID != ""},
		SubjectUserID:   sql.NullString{String: SubjectUserID, Valid: SubjectUserID != ""},
		GroupID:         sql.NullString{String: GroupID, Valid: GroupID != ""},
		Status:          sql.NullString{String: Status, Valid: Status != ""},
		OrgIds:          OrgIds,
		RowOffset:       RowOffset,
		RowLimit:        RowLimit,
	})
	if err != nil {
		return nil, err
	}
	res := make([]*AccessRequestModel, len(rows))
	for i, row := range rows {
		res[i] = &AccessRequestModel{
			ID:              row.ID,
			RequesterUserID: row.RequesterUserID,
			SubjectUserID:   row.SubjectUserID,
			GroupID:         row.GroupID,
			Reason:          row.Reason,
			RequestedUntil:  row.RequestedUntil,
			Status:          row.Status,
			Origin:          row.Origin,
			SessionID:       row.SessionID.String,
			DecidedByUserID: row.DecidedByUserID.String,
			DecidedAt:       row.DecidedAt,
			DecisionComment: row.DecisionComment,
			CreatedAt:       row.CreatedAt,
			UpdatedAt:       row.UpdatedAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) ListAgents(ctx context.Context, OrgID string, ParentAgentID string, OrgIds []string, RowOffset int32, RowLimit int32) ([]*AgentModel, error) {
	rows, err := p.q.ListAgents(ctx, postgressqlc.ListAgentsParams{
		OrgID:         sql.NullString{String: OrgID, Valid: OrgID != ""},
		ParentAgentID: sql.NullString{String: ParentAgentID, Valid: ParentAgentID != ""},
		OrgIds:        OrgIds,
		RowOffset:     RowOffset,
		RowLimit:      RowLimit,
	})
	if err != nil {
		return nil, err
	}
	res := make([]*AgentModel, len(rows))
	for i, row := range rows {
		res[i] = &AgentModel{
			ID:              row.ID,
			OrgID:           row.OrgID,
			UserID:          row.UserID,
			Name:            row.Name,
			Description:     row.Description,
			ClientID:        row.ClientID,
			KeycloakID:      row.KeycloakID,
			AuthMethod:      row.AuthMethod,
			SecretRotatedAt: row.SecretRotatedAt,
			ParentAgentID:   row.ParentAgentID.String,
			CreatedByUserID: row.CreatedByUserID,
			CreatedAt:       row.CreatedAt,
			UpdatedAt:       row.UpdatedAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) ListServiceAccounts(ctx context.Context, RowOffset int32, RowLimit int32) ([]*ServiceAccountModel, error) {
	rows, err := p.q.ListServiceAccounts(ctx, postgressqlc.ListServiceAccountsParams{
		RowOffset: RowOffset,
		RowLimit:  RowLimit,
	})
	if err != nil {
		return nil, err
	}
	res := make([]*ServiceAccountModel, len(rows))
	for i, row := range rows {
		res[i] = &ServiceAccountModel{
			ID:              row.ID,
			UserID:          row.UserID,
			Name:            row.Name,
			Description:     row.Description,
			ClientID:        row.ClientID,
			KeycloakID:      row.KeycloakID,
			CreatedByUserID: row.CreatedByUserID,
			CreatedAt:       row.CreatedAt,
			UpdatedAt:       row.UpdatedAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) RecordAgentSecretRotation(ctx context.Context, id string) error {
	return p.q.RecordAgentSecretRotation(ctx, id)

}

func (p *PostgreSQLQuerier) RemoveAllUsersFromGroup(ctx context.Context, groupID string) error {
	return p.q.RemoveAllUsersFromGroup(ctx, groupID)

}

func (p *PostgreSQLQuerier) RemovePermissionFromRole(ctx context.Context, RoleID string, PermissionID string) error {
	return p.q.RemovePermissionFromRole(ctx, postgressqlc.RemovePermissionFromRoleParams{
		RoleID:       RoleID,
		PermissionID: PermissionID,
	})

}

func (p *PostgreSQLQuerier) SelectAccessPath(ctx context.Context) ([]*SelectAccessPathsModel, error) {
	rows, err := p.q.SelectAccessPaths(ctx)
	if err != nil {
		return nil, err
	}
	res := make([]*SelectAccessPathsModel, len(rows))
	for i, row := range rows {
		res[i] = &SelectAccessPathsModel{
			GroupID:      row.GroupID,
			GroupName:    row.GroupName,
			RoleID:       row.RoleID,
			RoleName:     row.RoleName,
			PermissionID: row.PermissionID,
			Identifier:   row.Identifier,
			Verb:         row.Verb,
			ExpiresAt:    row.ExpiresAt,
			OrgID:        row.OrgID,
			OrgName:      row.OrgName,
			OrgKind:      row.OrgKind,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectAccessRequest(ctx context.Context, id string) (*AccessRequestModel, error) {
	row, err := p.q.SelectAccessRequest(ctx, id)
	if err != nil {
		return nil, err
	}
	return &AccessRequestModel{
		ID:              row.ID,
		RequesterUserID: row.RequesterUserID,
		SubjectUserID:   row.SubjectUserID,
		GroupID:         row.GroupID,
		Reason:          row.Reason,
		RequestedUntil:  row.RequestedUntil,
		Status:          row.Status,
		Origin:          row.Origin,
		SessionID:       row.SessionID.String,
		DecidedByUserID: row.DecidedByUserID.String,
		DecidedAt:       row.DecidedAt,
		DecisionComment: row.DecisionComment,
		CreatedAt:       row.CreatedAt,
		UpdatedAt:       row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectAgent(ctx context.Context, id string) (*AgentModel, error) {
	row, err := p.q.SelectAgent(ctx, id)
	if err != nil {
		return nil, err
	}
	return &AgentModel{
		ID:              row.ID,
		OrgID:           row.OrgID,
		UserID:          row.UserID,
		Name:            row.Name,
		Description:     row.Description,
		ClientID:        row.ClientID,
		KeycloakID:      row.KeycloakID,
		AuthMethod:      row.AuthMethod,
		SecretRotatedAt: row.SecretRotatedAt,
		ParentAgentID:   row.ParentAgentID.String,
		CreatedByUserID: row.CreatedByUserID,
		CreatedAt:       row.CreatedAt,
		UpdatedAt:       row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectChatMessagesBySessionId(ctx context.Context, SessionID string, UserID string) ([]*ChatMessageModel, error) {
	rows, err := p.q.SelectChatMessagesBySessionId(ctx, postgressqlc.SelectChatMessagesBySessionIdParams{
		SessionID: SessionID,
		UserID:    UserID,
	})
	if err != nil {
		return nil, err
	}
	res := make([]*ChatMessageModel, len(rows))
	for i, row := range rows {
		res[i] = &ChatMessageModel{
			ID:        row.ID,
			SessionID: row.SessionID,
			Role:      row.Role,
			Content:   row.Content,
			CreatedAt: row.CreatedAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectChatSessionById(ctx context.Context, ID string, UserID string) (*ChatSessionModel, error) {
	row, err := p.q.SelectChatSessionById(ctx, postgressqlc.SelectChatSessionByIdParams{
		ID:     ID,
		UserID: UserID,
	})
	if err != nil {
		return nil, err
	}
	return &ChatSessionModel{
		ID:         row.ID,
		UserID:     row.UserID,
		Title:      row.Title,
		CreatedAt:  row.CreatedAt,
		TokensUsed: row.TokensUsed,
	}, nil

}

func (p *PostgreSQLQuerier) SelectChatSessionsByUserId(ctx context.Context, userID string) ([]*ChatSessionModel, error) {
	rows, err := p.q.SelectChatSessionsByUserId(ctx, userID)
	if err != nil {
		return nil, err
	}
	res := make([]*ChatSessionModel, len(rows))
	for i, row := range rows {
		res[i] = &ChatSessionModel{
			ID:         row.ID,
			UserID:     row.UserID,
			Title:      row.Title,
			CreatedAt:  row.CreatedAt,
			TokensUsed: row.TokensUsed,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectChatToolProposalById(ctx context.Context, ID string, UserID string) (*ChatToolProposalModel, error) {
	row, err := p.q.SelectChatToolProposalById(ctx, postgressqlc.SelectChatToolProposalByIdParams{
		ID:     ID,
		UserID: UserID,
	})
	if err != nil {
		return nil, err
	}
	return &ChatToolProposalModel{
		ID:           row.ID,
		SessionID:    row.SessionID,
		ToolName:     row.ToolName,
		Arguments:    row.Arguments,
		Continuation: row.Continuation,
		Status:       row.Status,
		CreatedAt:    row.CreatedAt,
		DecidedAt:    row.DecidedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectGroupById(ctx context.Context, id string) (*GroupModel, error) {
	row, err := p.q.SelectGroupById(ctx, id)
	if err != nil {
		return nil, err
	}
	return &GroupModel{
		ID:          row.ID,
		Name:        row.Name,
		Description: row.Description,
		Status:      row.Status,
		OrgID:       row.OrgID,
		CreatedAt:   row.CreatedAt,
		UpdatedAt:   row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectGroupForUpdate(ctx context.Context, id string) (*GroupModel, error) {
	row, err := p.q.SelectGroupForUpdate(ctx, id)
	if err != nil {
		return nil, err
	}
	return &GroupModel{
		ID:          row.ID,
		Name:        row.Name,
		Description: row.Description,
		Status:      row.Status,
		OrgID:       row.OrgID,
		CreatedAt:   row.CreatedAt,
		UpdatedAt:   row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectGroupRoleByGroupId(ctx context.Context, groupID string) ([]*GroupRoleModel, error) {
	rows, err := p.q.SelectGroupRoleByGroupId(ctx, groupID)
	if err != nil {
		return nil, err
	}
	res := make([]*GroupRoleModel, len(rows))
	for i, row := range rows {
		res[i] = &GroupRoleModel{
			GroupID:   row.GroupID,
			RoleID:    row.RoleID,
			ExpiresAt: row.ExpiresAt,
			CreatedAt: row.CreatedAt,
			UpdatedAt: row.UpdatedAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectMembership(ctx context.Context) ([]*SelectMembershipsModel, error) {
	rows, err := p.q.SelectMemberships(ctx)
	if err != nil {
		return nil, err
	}
	res := make([]*SelectMembershipsModel, len(rows))
	for i, row := range rows {
		res[i] = &SelectMembershipsModel{
			ID:        row.ID,
			Username:  row.Username,
			GroupID:   row.GroupID,
			ExpiresAt: row.ExpiresAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectOrganization(ctx context.Context, id string) (*OrganizationModel, error) {
	row, err := p.q.SelectOrganization(ctx, id)
	if err != nil {
		return nil, err
	}
	return &OrganizationModel{
		ID:          row.ID,
		Name:        row.Name,
		Slug:        row.Slug,
		Kind:        row.Kind,
		Description: row.Description,
		Status:      row.Status,
		CreatedAt:   row.CreatedAt,
		UpdatedAt:   row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectOrganizationBySlug(ctx context.Context, slug string) (*OrganizationModel, error) {
	row, err := p.q.SelectOrganizationBySlug(ctx, slug)
	if err != nil {
		return nil, err
	}
	return &OrganizationModel{
		ID:          row.ID,
		Name:        row.Name,
		Slug:        row.Slug,
		Kind:        row.Kind,
		Description: row.Description,
		Status:      row.Status,
		CreatedAt:   row.CreatedAt,
		UpdatedAt:   row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectPermissionById(ctx context.Context, id string) (*PermissionModel, error) {
	row, err := p.q.SelectPermissionById(ctx, id)
	if err != nil {
		return nil, err
	}
	return &PermissionModel{
		ID:          row.ID,
		Verb:        row.Verb,
		ResourceID:  row.ResourceID,
		Description: row.Description,
		CreatedAt:   row.CreatedAt,
		UpdatedAt:   row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectPermissionByResourceId(ctx context.Context, resourceID string) ([]*PermissionModel, error) {
	rows, err := p.q.SelectPermissionByResourceId(ctx, resourceID)
	if err != nil {
		return nil, err
	}
	res := make([]*PermissionModel, len(rows))
	for i, row := range rows {
		res[i] = &PermissionModel{
			ID:          row.ID,
			Verb:        row.Verb,
			ResourceID:  row.ResourceID,
			Description: row.Description,
			CreatedAt:   row.CreatedAt,
			UpdatedAt:   row.UpdatedAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectPermissionForUpdate(ctx context.Context, id string) (*PermissionModel, error) {
	row, err := p.q.SelectPermissionForUpdate(ctx, id)
	if err != nil {
		return nil, err
	}
	return &PermissionModel{
		ID:          row.ID,
		Verb:        row.Verb,
		ResourceID:  row.ResourceID,
		Description: row.Description,
		CreatedAt:   row.CreatedAt,
		UpdatedAt:   row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectRbacRevision(ctx context.Context) (int64, error) {
	row, err := p.q.SelectRbacRevision(ctx)
	if err != nil {
		return 0, err
	}
	return row, nil

}

func (p *PostgreSQLQuerier) SelectResourceById(ctx context.Context, id string) (*ResourceModel, error) {
	row, err := p.q.SelectResourceById(ctx, id)
	if err != nil {
		return nil, err
	}
	var metadata map[string]string
	if row.Metadata.Valid {
		_ = json.Unmarshal(row.Metadata.RawMessage, &metadata)
	}
	return &ResourceModel{
		ID:           row.ID,
		ParentID:     row.ParentID.String,
		Name:         row.Name,
		Identifier:   row.Identifier,
		Type:         row.Type,
		Path:         row.Path.String,
		Component:    row.Component.String,
		DisplayOrder: row.DisplayOrder.Int32,
		Description:  row.Description,
		Metadata:     metadata,
		Status:       row.Status,
		CreatedAt:    row.CreatedAt,
		UpdatedAt:    row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectResourceByIdentifier(ctx context.Context, identifier string) (*ResourceModel, error) {
	row, err := p.q.SelectResourceByIdentifier(ctx, identifier)
	if err != nil {
		return nil, err
	}
	var metadata map[string]string
	if row.Metadata.Valid {
		_ = json.Unmarshal(row.Metadata.RawMessage, &metadata)
	}
	return &ResourceModel{
		ID:           row.ID,
		ParentID:     row.ParentID.String,
		Name:         row.Name,
		Identifier:   row.Identifier,
		Type:         row.Type,
		Path:         row.Path.String,
		Component:    row.Component.String,
		DisplayOrder: row.DisplayOrder.Int32,
		Description:  row.Description,
		Metadata:     metadata,
		Status:       row.Status,
		CreatedAt:    row.CreatedAt,
		UpdatedAt:    row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectResourceForUpdate(ctx context.Context, id string) (*ResourceModel, error) {
	row, err := p.q.SelectResourceForUpdate(ctx, id)
	if err != nil {
		return nil, err
	}
	var metadata map[string]string
	if row.Metadata.Valid {
		_ = json.Unmarshal(row.Metadata.RawMessage, &metadata)
	}
	return &ResourceModel{
		ID:           row.ID,
		ParentID:     row.ParentID.String,
		Name:         row.Name,
		Identifier:   row.Identifier,
		Type:         row.Type,
		Path:         row.Path.String,
		Component:    row.Component.String,
		DisplayOrder: row.DisplayOrder.Int32,
		Description:  row.Description,
		Metadata:     metadata,
		Status:       row.Status,
		CreatedAt:    row.CreatedAt,
		UpdatedAt:    row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectRoleById(ctx context.Context, id string) (*RoleModel, error) {
	row, err := p.q.SelectRoleById(ctx, id)
	if err != nil {
		return nil, err
	}
	return &RoleModel{
		ID:          row.ID,
		Name:        row.Name,
		Description: row.Description,
		OrgID:       row.OrgID.String,
		CreatedAt:   row.CreatedAt,
		UpdatedAt:   row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectRoleForUpdate(ctx context.Context, id string) (*RoleModel, error) {
	row, err := p.q.SelectRoleForUpdate(ctx, id)
	if err != nil {
		return nil, err
	}
	return &RoleModel{
		ID:          row.ID,
		Name:        row.Name,
		Description: row.Description,
		OrgID:       row.OrgID.String,
		CreatedAt:   row.CreatedAt,
		UpdatedAt:   row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectRolePermissionByRoleId(ctx context.Context, roleID string) ([]*RolePermissionModel, error) {
	rows, err := p.q.SelectRolePermissionByRoleId(ctx, roleID)
	if err != nil {
		return nil, err
	}
	res := make([]*RolePermissionModel, len(rows))
	for i, row := range rows {
		res[i] = &RolePermissionModel{
			RoleID:       row.RoleID,
			PermissionID: row.PermissionID,
			CreatedAt:    row.CreatedAt,
			UpdatedAt:    row.UpdatedAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectServiceAccount(ctx context.Context, id string) (*ServiceAccountModel, error) {
	row, err := p.q.SelectServiceAccount(ctx, id)
	if err != nil {
		return nil, err
	}
	return &ServiceAccountModel{
		ID:              row.ID,
		UserID:          row.UserID,
		Name:            row.Name,
		Description:     row.Description,
		ClientID:        row.ClientID,
		KeycloakID:      row.KeycloakID,
		CreatedByUserID: row.CreatedByUserID,
		CreatedAt:       row.CreatedAt,
		UpdatedAt:       row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectUserAccessPath(ctx context.Context, id string) ([]*SelectUserAccessPathsModel, error) {
	rows, err := p.q.SelectUserAccessPaths(ctx, id)
	if err != nil {
		return nil, err
	}
	res := make([]*SelectUserAccessPathsModel, len(rows))
	for i, row := range rows {
		res[i] = &SelectUserAccessPathsModel{
			GroupID:        row.GroupID,
			GroupName:      row.GroupName,
			RoleID:         row.RoleID,
			RoleName:       row.RoleName,
			PermissionID:   row.PermissionID,
			Identifier:     row.Identifier,
			Verb:           row.Verb,
			GroupExpiresAt: row.GroupExpiresAt,
			RoleExpiresAt:  row.RoleExpiresAt,
			OrgID:          row.OrgID,
			OrgName:        row.OrgName,
			OrgKind:        row.OrgKind,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectUserAuthorizedPolicies(ctx context.Context, id string) ([]*SelectUserAuthorizedPolicesModel, error) {
	rows, err := p.q.SelectUserAuthorizedPolices(ctx, id)
	if err != nil {
		return nil, err
	}
	res := make([]*SelectUserAuthorizedPolicesModel, len(rows))
	for i, row := range rows {
		res[i] = &SelectUserAuthorizedPolicesModel{
			ID:             row.ID,
			Identifier:     row.Identifier,
			Verb:           row.Verb,
			GroupExpiresAt: row.GroupExpiresAt,
			RoleExpiresAt:  row.RoleExpiresAt,
			OrgID:          row.OrgID,
			OrgKind:        row.OrgKind,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectUserById(ctx context.Context, id string) (*UserModel, error) {
	row, err := p.q.SelectUserById(ctx, id)
	if err != nil {
		return nil, err
	}
	return &UserModel{
		ID:        row.ID,
		Username:  row.Username,
		Email:     row.Email,
		Status:    row.Status,
		CreatedAt: row.CreatedAt,
		UpdatedAt: row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectUserForUpdate(ctx context.Context, id string) (*UserModel, error) {
	row, err := p.q.SelectUserForUpdate(ctx, id)
	if err != nil {
		return nil, err
	}
	return &UserModel{
		ID:        row.ID,
		Username:  row.Username,
		Email:     row.Email,
		Status:    row.Status,
		CreatedAt: row.CreatedAt,
		UpdatedAt: row.UpdatedAt,
	}, nil

}

func (p *PostgreSQLQuerier) SelectUserGroupByGroupId(ctx context.Context, groupID string) ([]*UserGroupModel, error) {
	rows, err := p.q.SelectUserGroupByGroupId(ctx, groupID)
	if err != nil {
		return nil, err
	}
	res := make([]*UserGroupModel, len(rows))
	for i, row := range rows {
		res[i] = &UserGroupModel{
			UserID:    row.UserID,
			GroupID:   row.GroupID,
			ExpiresAt: row.ExpiresAt,
			CreatedAt: row.CreatedAt,
			UpdatedAt: row.UpdatedAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectUserGroupByUserId(ctx context.Context, userID string) ([]*UserGroupModel, error) {
	rows, err := p.q.SelectUserGroupByUserId(ctx, userID)
	if err != nil {
		return nil, err
	}
	res := make([]*UserGroupModel, len(rows))
	for i, row := range rows {
		res[i] = &UserGroupModel{
			UserID:    row.UserID,
			GroupID:   row.GroupID,
			ExpiresAt: row.ExpiresAt,
			CreatedAt: row.CreatedAt,
			UpdatedAt: row.UpdatedAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) SelectUserOrganization(ctx context.Context, userID string) ([]*OrganizationModel, error) {
	rows, err := p.q.SelectUserOrganizations(ctx, userID)
	if err != nil {
		return nil, err
	}
	res := make([]*OrganizationModel, len(rows))
	for i, row := range rows {
		res[i] = &OrganizationModel{
			ID:          row.ID,
			Name:        row.Name,
			Slug:        row.Slug,
			Kind:        row.Kind,
			Description: row.Description,
			Status:      row.Status,
			CreatedAt:   row.CreatedAt,
			UpdatedAt:   row.UpdatedAt,
		}
	}
	return res, nil

}

func (p *PostgreSQLQuerier) UpdateGroup(ctx context.Context, Name string, Description string, Status string, ID string) error {
	return p.q.UpdateGroup(ctx, postgressqlc.UpdateGroupParams{
		Name:        Name,
		Description: Description,
		Status:      Status,
		ID:          ID,
	})

}

func (p *PostgreSQLQuerier) UpdateOrganization(ctx context.Context, Name string, Slug string, Description string, Status string, ID string) error {
	return p.q.UpdateOrganization(ctx, postgressqlc.UpdateOrganizationParams{
		Name:        Name,
		Slug:        Slug,
		Description: Description,
		Status:      Status,
		ID:          ID,
	})

}

func (p *PostgreSQLQuerier) UpdatePermission(ctx context.Context, Verb string, ResourceID string, Description string, ID string) error {
	return p.q.UpdatePermission(ctx, postgressqlc.UpdatePermissionParams{
		Verb:        Verb,
		ResourceID:  ResourceID,
		Description: Description,
		ID:          ID,
	})

}

func (p *PostgreSQLQuerier) UpdateResource(ctx context.Context, ParentID string, Name string, Identifier string, Type string, Path string, Component string, DisplayOrder int32, Description string, Metadata map[string]string, Status string, ID string) error {
	m, _ := json.Marshal(Metadata)
	return p.q.UpdateResource(ctx, postgressqlc.UpdateResourceParams{
		ParentID:     sql.NullString{String: ParentID, Valid: ParentID != ""},
		Name:         Name,
		Identifier:   Identifier,
		Type:         Type,
		Path:         sql.NullString{String: Path, Valid: Path != ""},
		Component:    sql.NullString{String: Component, Valid: Component != ""},
		DisplayOrder: sql.NullInt32{Int32: DisplayOrder, Valid: true},
		Description:  Description,
		Metadata:     pqtype.NullRawMessage{RawMessage: m, Valid: m != nil},
		Status:       Status,
		ID:           ID,
	})

}

func (p *PostgreSQLQuerier) UpdateRole(ctx context.Context, Name string, Description string, ID string) error {
	return p.q.UpdateRole(ctx, postgressqlc.UpdateRoleParams{
		Name:        Name,
		Description: Description,
		ID:          ID,
	})

}

func (p *PostgreSQLQuerier) UpdateUser(ctx context.Context, Username string, Email string, Status string, ID string) error {
	return p.q.UpdateUser(ctx, postgressqlc.UpdateUserParams{
		Username: Username,
		Email:    Email,
		Status:   Status,
		ID:       ID,
	})

}

// NewQuerierAdapter creates the appropriate Querier adapter
func NewQuerierAdapter(queries any) Querier {
	if q, ok := queries.(Querier); ok {
		return q
	}
	if q, ok := queries.(*postgressqlc.Queries); ok {
		return NewPostgreSQLQuerier(q)
	}
	return nil
}

// GetQuerier returns a new Querier instance
func GetQuerier(db *sql.DB) Querier {
	return NewPostgreSQLQuerier(postgressqlc.New(db))
}
