// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accessrequest.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const countAccessRequests = `-- name: CountAccessRequests :one
SELECT count(*)
FROM access_requests
WHERE ($1::uuid IS NULL OR requester_user_id = $1::uuid)
  AND ($2::uuid IS NULL OR subject_user_id = $2::uuid)
  AND ($3::uuid IS NULL OR group_id = $3::uuid)
  AND ($4::varchar IS NULL OR status = $4::varchar)
  AND ($5::uuid[] IS NULL
       OR group_id IN (SELECT id FROM "groups" WHERE org_id = ANY ($5::uuid[])))
`

type CountAccessRequestsParams struct {
	RequesterUserID sql.NullString
	SubjectUserID   sql.NullString
	GroupID         sql.NullString
	Status          sql.NullString
	OrgIds          []string
}

func (q *Queries) CountAccessRequests(ctx context.Context, arg CountAccessRequestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccessRequests,
		arg.RequesterUserID,
		arg.SubjectUserID,
		arg.GroupID,
		arg.Status,
		pq.Array(arg.OrgIds),
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccessRequest = `-- name: CreateAccessRequest :exec
INSERT INTO access_requests (id,
                             requester_user_id,
                             subject_user_id,
                             group_id,
                             reason,
                             requested_until,
                             status,
                             origin,
                             session_id,
                             created_at,
                             updated_at)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        now(),
        now())
`

type CreateAccessRequestParams struct {
	ID              string
	RequesterUserID string
	SubjectUserID   string
	GroupID         string
	Reason          string
	RequestedUntil  sql.NullTime
	Status          string
	Origin          string
	SessionID       sql.NullString
}

func (q *Queries) CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) error {
	_, err := q.db.ExecContext(ctx, createAccessRequest,
		arg.ID,
		arg.RequesterUserID,
		arg.SubjectUserID,
		arg.GroupID,
		arg.Reason,
		arg.RequestedUntil,
		arg.Status,
		arg.Origin,
		arg.SessionID,
	)
	return err
}

const decideAccessRequest = `-- name: DecideAccessRequest :one
UPDATE access_requests
SET status             = $1,
    decided_by_user_id = $2,
    decided_at         = $3,
    decision_comment   = $4
WHERE id = $5
  AND status = 'Pending'
RETURNING id, requester_user_id, subject_user_id, group_id, reason, requested_until, status, origin, session_id, decided_by_user_id, decided_at, decision_comment, created_at, updated_at
`

type DecideAccessRequestParams struct {
	Status          string
	DecidedByUserID sql.NullString
	DecidedAt       sql.NullTime
	DecisionComment string
	ID              string
}

// Deciding is conditional on the request still being pending, so two decisions
// racing cannot both grant the access: the second updates no row.
func (q *Queries) DecideAccessRequest(ctx context.Context, arg DecideAccessRequestParams) (*AccessRequest, error) {
	row := q.db.QueryRowContext(ctx, decideAccessRequest,
		arg.Status,
		arg.DecidedByUserID,
		arg.DecidedAt,
		arg.DecisionComment,
		arg.ID,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserID,
		&i.SubjectUserID,
		&i.GroupID,
		&i.Reason,
		&i.RequestedUntil,
		&i.Status,
		&i.Origin,
		&i.SessionID,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAccessRequests = `-- name: ListAccessRequests :many
SELECT id, requester_user_id, subject_user_id, group_id, reason, requested_until, status, origin, session_id, decided_by_user_id, decided_at, decision_comment, created_at, updated_at
FROM access_requests
WHERE ($1::uuid IS NULL OR requester_user_id = $1::uuid)
  AND ($2::uuid IS NULL OR subject_user_id = $2::uuid)
  AND ($3::uuid IS NULL OR group_id = $3::uuid)
  AND ($4::varchar IS NULL OR status = $4::varchar)
  AND ($5::uuid[] IS NULL
       OR group_id IN (SELECT id FROM "groups" WHERE org_id = ANY ($5::uuid[])))
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type ListAccessRequestsParams struct {
	RequesterUserID sql.NullString
	SubjectUserID   sql.NullString
	GroupID         sql.NullString
	Status          sql.NullString
	OrgIds          []string
	RowOffset       int32
	RowLimit        int32
}

// Every filter is optional and written as "unset or matching", so one query
// serves the approver's queue ("pending"), the requester's own list ("mine")
// and a group's history without three near-identical statements.
// Newest first: a queue is read from the top.
func (q *Queries) ListAccessRequests(ctx context.Context, arg ListAccessRequestsParams) ([]*AccessRequest, error) {
	rows, err := q.db.QueryContext(ctx, listAccessRequests,
		arg.RequesterUserID,
		arg.SubjectUserID,
		arg.GroupID,
		arg.Status,
		pq.Array(arg.OrgIds),
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AccessRequest{}
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserID,
			&i.SubjectUserID,
			&i.GroupID,
			&i.Reason,
			&i.RequestedUntil,
			&i.Status,
			&i.Origin,
			&i.SessionID,
			&i.DecidedByUserID,
			&i.DecidedAt,
			&i.DecisionComment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAccessRequest = `-- name: SelectAccessRequest :one
SELECT id, requester_user_id, subject_user_id, group_id, reason, requested_until, status, origin, session_id, decided_by_user_id, decided_at, decision_comment, created_at, updated_at
FROM access_requests
WHERE id = $1
LIMIT 1
`

func (q *Queries) SelectAccessRequest(ctx context.Context, id string) (*AccessRequest, error) {
	row := q.db.QueryRowContext(ctx, selectAccessRequest, id)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserID,
		&i.SubjectUserID,
		&i.GroupID,
		&i.Reason,
		&i.RequestedUntil,
		&i.Status,
		&i.Origin,
		&i.SessionID,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
