// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const countAgentChildren = `-- name: CountAgentChildren :one
SELECT count(*)
FROM agents
WHERE parent_agent_id = $1::uuid
`

// An agent with children cannot be removed: deleting it would leave their
// credentials working with nothing in hub recording them. The count is asked
// before anything is touched rather than left to the foreign key to refuse
// half-way through the delete.
func (q *Queries) CountAgentChildren(ctx context.Context, parentAgentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentChildren, parentAgentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgents = `-- name: CountAgents :one
SELECT count(*)
FROM agents
WHERE ($1::uuid IS NULL OR org_id = $1::uuid)
  AND ($2::uuid IS NULL OR parent_agent_id = $2::uuid)
  AND ($3::uuid[] IS NULL OR org_id = ANY ($3::uuid[]))
`

type CountAgentsParams struct {
	OrgID         sql.NullString
	ParentAgentID sql.NullString
	OrgIds        []string
}

func (q *Queries) CountAgents(ctx context.Context, arg CountAgentsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgents, arg.OrgID, arg.ParentAgentID, pq.Array(arg.OrgIds))
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (id,
                    org_id,
                    user_id,
                    name,
                    description,
                    client_id,
                    keycloak_id,
                    auth_method,
                    parent_agent_id,
                    created_by_user_id,
                    secret_rotated_at,
                    created_at,
                    updated_at)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        now(),
        now(),
        now())
`

type CreateAgentParams struct {
	ID              string
	OrgID           string
	UserID          string
	Name            string
	Description     string
	ClientID        string
	KeycloakID      string
	AuthMethod      string
	ParentAgentID   sql.NullString
	CreatedByUserID string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ClientID,
		arg.KeycloakID,
		arg.AuthMethod,
		arg.ParentAgentID,
		arg.CreatedByUserID,
	)
	return err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE
FROM agents
WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const listAgents = `-- name: ListAgents :many
SELECT id, org_id, user_id, name, description, client_id, keycloak_id, auth_method, secret_rotated_at, parent_agent_id, created_by_user_id, created_at, updated_at
FROM agents
WHERE ($1::uuid IS NULL OR org_id = $1::uuid)
  AND ($2::uuid IS NULL OR parent_agent_id = $2::uuid)
  AND ($3::uuid[] IS NULL OR org_id = ANY ($3::uuid[]))
ORDER BY name
LIMIT $5 OFFSET $4
`

type ListAgentsParams struct {
	OrgID         sql.NullString
	ParentAgentID sql.NullString
	OrgIds        []string
	RowOffset     int32
	RowLimit      int32
}

// Every filter is optional and written as "unset or matching". org_ids is the
// caller's reach rather than a filter they asked for: NULL is a platform grant,
// which answers about every organization, and any other value is the set they
// hold a live grant in. Listing every agent would tell one customer which
// agents another runs.
func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]*Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents,
		arg.OrgID,
		arg.ParentAgentID,
		pq.Array(arg.OrgIds),
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.KeycloakID,
			&i.AuthMethod,
			&i.SecretRotatedAt,
			&i.ParentAgentID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAgentSecretRotation = `-- name: RecordAgentSecretRotation :exec
UPDATE agents
SET secret_rotated_at = now()
WHERE id = $1
`

func (q *Queries) RecordAgentSecretRotation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, recordAgentSecretRotation, id)
	return err
}

const selectAgent = `-- name: SelectAgent :one
SELECT id, org_id, user_id, name, description, client_id, keycloak_id, auth_method, secret_rotated_at, parent_agent_id, created_by_user_id, created_at, updated_at
FROM agents
WHERE id = $1
LIMIT 1
`

func (q *Queries) SelectAgent(ctx context.Context, id string) (*Agent, error) {
	row := q.db.QueryRowContext(ctx, selectAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.KeycloakID,
		&i.AuthMethod,
		&i.SecretRotatedAt,
		&i.ParentAgentID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
