// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const selectAccessPaths = `-- name: SelectAccessPaths :many
SELECT g.id     AS group_id,
       g.name   AS group_name,
       r.id     AS role_id,
       r.name   AS role_name,
       p.id     AS permission_id,
       res.identifier,
       p.verb,
       gr.expires_at
FROM "groups" AS g
         INNER JOIN group_roles AS gr ON g.id = gr.group_id
         INNER JOIN roles AS r ON r.id = gr.role_id
         INNER JOIN role_permissions AS rp ON gr.role_id = rp.role_id
         INNER JOIN permissions AS p ON rp.permission_id = p.id
         INNER JOIN resources AS res ON p.resource_id = res.id AND res.status = 'Active'
WHERE g.status = 'Active'
ORDER BY g.name, r.name, res.identifier, p.verb
`

type SelectAccessPathsRow struct {
	GroupID      string
	GroupName    string
	RoleID       string
	RoleName     string
	PermissionID string
	Identifier   string
	Verb         string
	ExpiresAt    sql.NullTime
}

func (q *Queries) SelectAccessPaths(ctx context.Context) ([]*SelectAccessPathsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectAccessPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SelectAccessPathsRow{}
	for rows.Next() {
		var i SelectAccessPathsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.RoleID,
			&i.RoleName,
			&i.PermissionID,
			&i.Identifier,
			&i.Verb,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMemberships = `-- name: SelectMemberships :many
SELECT u.id,
       u.username,
       ug.group_id,
       ug.expires_at
FROM users AS u
         INNER JOIN user_groups AS ug ON u.id = ug.user_id
WHERE u.status = 'Active'
ORDER BY u.username, u.id
`

type SelectMembershipsRow struct {
	ID        string
	Username  string
	GroupID   string
	ExpiresAt sql.NullTime
}

func (q *Queries) SelectMemberships(ctx context.Context) ([]*SelectMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SelectMembershipsRow{}
	for rows.Next() {
		var i SelectMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.GroupID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserAccessPaths = `-- name: SelectUserAccessPaths :many
SELECT g.id     AS group_id,
       g.name   AS group_name,
       r.id     AS role_id,
       r.name   AS role_name,
       p.id     AS permission_id,
       res.identifier,
       p.verb,
       ug.expires_at AS group_expires_at,
       gr.expires_at AS role_expires_at
FROM users AS u
         INNER JOIN user_groups AS ug ON u.id = ug.user_id
         INNER JOIN "groups" AS g ON g.id = ug.group_id AND g.status = 'Active'
         INNER JOIN group_roles AS gr ON ug.group_id = gr.group_id
         INNER JOIN roles AS r ON r.id = gr.role_id
         INNER JOIN role_permissions AS rp ON gr.role_id = rp.role_id
         INNER JOIN permissions AS p ON rp.permission_id = p.id
         INNER JOIN resources AS res ON p.resource_id = res.id AND res.status = 'Active'
WHERE u.id = $1
  AND u.status = 'Active'
ORDER BY g.name, r.name, res.identifier, p.verb
`

type SelectUserAccessPathsRow struct {
	GroupID        string
	GroupName      string
	RoleID         string
	RoleName       string
	PermissionID   string
	Identifier     string
	Verb           string
	GroupExpiresAt sql.NullTime
	RoleExpiresAt  sql.NullTime
}

func (q *Queries) SelectUserAccessPaths(ctx context.Context, id string) ([]*SelectUserAccessPathsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectUserAccessPaths, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SelectUserAccessPathsRow{}
	for rows.Next() {
		var i SelectUserAccessPathsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.RoleID,
			&i.RoleName,
			&i.PermissionID,
			&i.Identifier,
			&i.Verb,
			&i.GroupExpiresAt,
			&i.RoleExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserAuthorizedPolices = `-- name: SelectUserAuthorizedPolices :many
SELECT u.id, res.identifier, p.verb, ug.expires_at AS group_expires_at, gr.expires_at AS role_expires_at
FROM users AS u
         INNER JOIN user_groups AS ug ON u.id = ug.user_id
         INNER JOIN "groups" AS g ON g.id = ug.group_id AND g.status = 'Active'
         INNER JOIN group_roles AS gr ON ug.group_id = gr.group_id
         INNER JOIN role_permissions AS rp ON gr.role_id = rp.role_id
         INNER JOIN permissions AS p ON rp.permission_id = p.id
         INNER JOIN resources AS res ON p.resource_id = res.id AND res.status = 'Active'
WHERE u.id = $1
  AND u.status = 'Active'
`

type SelectUserAuthorizedPolicesRow struct {
	ID             string
	Identifier     string
	Verb           string
	GroupExpiresAt sql.NullTime
	RoleExpiresAt  sql.NullTime
}

// The expiry is not filtered here on purpose: see the note on expires_at in
// the user_groups and group_roles migrations.
//
// Both edges of the route are returned rather than LEAST() of them, so that
// "the route expires with whichever edge expires first" is stated once, in Go,
// where it is under test - and so that a NULL keeps meaning "never" rather than
// depending on how LEAST treats it.
func (q *Queries) SelectUserAuthorizedPolices(ctx context.Context, id string) ([]*SelectUserAuthorizedPolicesRow, error) {
	rows, err := q.db.QueryContext(ctx, selectUserAuthorizedPolices, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SelectUserAuthorizedPolicesRow{}
	for rows.Next() {
		var i SelectUserAuthorizedPolicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.Verb,
			&i.GroupExpiresAt,
			&i.RoleExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
