// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package sqlc

import (
	"context"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (session_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, session_id, role, content, created_at
`

type CreateChatMessageParams struct {
	SessionID string
	Role      string
	Content   string
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (*ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage, arg.SessionID, arg.Role, arg.Content)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return &i, err
}

const createChatSession = `-- name: CreateChatSession :one
INSERT INTO chat_sessions (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at
`

type CreateChatSessionParams struct {
	UserID string
	Title  string
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (*ChatSession, error) {
	row := q.db.QueryRowContext(ctx, createChatSession, arg.UserID, arg.Title)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteChatSession = `-- name: DeleteChatSession :exec
DELETE
FROM chat_sessions
WHERE id = $1
  AND user_id = $2
`

type DeleteChatSessionParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteChatSession(ctx context.Context, arg DeleteChatSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteChatSession, arg.ID, arg.UserID)
	return err
}

const selectChatMessagesBySessionId = `-- name: SelectChatMessagesBySessionId :many
SELECT m.id, m.session_id, m.role, m.content, m.created_at
FROM chat_messages m
         JOIN chat_sessions s ON s.id = m.session_id
WHERE m.session_id = $1
  AND s.user_id = $2
ORDER BY m.created_at ASC
`

type SelectChatMessagesBySessionIdParams struct {
	SessionID string
	UserID    string
}

func (q *Queries) SelectChatMessagesBySessionId(ctx context.Context, arg SelectChatMessagesBySessionIdParams) ([]*ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, selectChatMessagesBySessionId, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectChatSessionById = `-- name: SelectChatSessionById :one
SELECT id, user_id, title, created_at
FROM chat_sessions
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type SelectChatSessionByIdParams struct {
	ID     string
	UserID string
}

// Scoping every lookup by user_id keeps a session private to its owner even if
// a caller reaches the repository without going through the use case, which is
// where the check used to live alone. A session belonging to someone else
// returns no row, so it is indistinguishable from one that does not exist.
func (q *Queries) SelectChatSessionById(ctx context.Context, arg SelectChatSessionByIdParams) (*ChatSession, error) {
	row := q.db.QueryRowContext(ctx, selectChatSessionById, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
	)
	return &i, err
}

const selectChatSessionsByUserId = `-- name: SelectChatSessionsByUserId :many
SELECT id, user_id, title, created_at
FROM chat_sessions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) SelectChatSessionsByUserId(ctx context.Context, userID string) ([]*ChatSession, error) {
	rows, err := q.db.QueryContext(ctx, selectChatSessionsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
