// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delegation.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const addPermissionToDelegation = `-- name: AddPermissionToDelegation :exec
INSERT INTO delegation_permissions (delegation_id, permission_id, created_at, updated_at)
VALUES ($1, $2, now(), now())
ON CONFLICT (delegation_id, permission_id) DO NOTHING
`

type AddPermissionToDelegationParams struct {
	DelegationID string
	PermissionID string
}

func (q *Queries) AddPermissionToDelegation(ctx context.Context, arg AddPermissionToDelegationParams) error {
	_, err := q.db.ExecContext(ctx, addPermissionToDelegation, arg.DelegationID, arg.PermissionID)
	return err
}

const countDelegations = `-- name: CountDelegations :one
SELECT count(*)
FROM delegations
WHERE ($1::uuid IS NULL OR agent_id = $1::uuid)
  AND ($2::uuid IS NULL OR principal_user_id = $2::uuid)
  AND ($3::bool OR revoked_at IS NULL)
  AND ($4::uuid[] IS NULL
       OR org_id = ANY ($4::uuid[])
       OR principal_user_id = $5::uuid)
`

type CountDelegationsParams struct {
	AgentID         sql.NullString
	PrincipalUserID sql.NullString
	IncludeRevoked  bool
	OrgIds          []string
	SelfUserID      sql.NullString
}

func (q *Queries) CountDelegations(ctx context.Context, arg CountDelegationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDelegations,
		arg.AgentID,
		arg.PrincipalUserID,
		arg.IncludeRevoked,
		pq.Array(arg.OrgIds),
		arg.SelfUserID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDelegation = `-- name: CreateDelegation :exec
INSERT INTO delegations (id,
                         agent_id,
                         principal_user_id,
                         granted_by_user_id,
                         org_id,
                         reason,
                         max_depth,
                         expires_at,
                         created_at,
                         updated_at)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        now(),
        now())
`

type CreateDelegationParams struct {
	ID              string
	AgentID         string
	PrincipalUserID string
	GrantedByUserID string
	OrgID           string
	Reason          string
	MaxDepth        int16
	ExpiresAt       sql.NullTime
}

func (q *Queries) CreateDelegation(ctx context.Context, arg CreateDelegationParams) error {
	_, err := q.db.ExecContext(ctx, createDelegation,
		arg.ID,
		arg.AgentID,
		arg.PrincipalUserID,
		arg.GrantedByUserID,
		arg.OrgID,
		arg.Reason,
		arg.MaxDepth,
		arg.ExpiresAt,
	)
	return err
}

const listDelegations = `-- name: ListDelegations :many
SELECT id, agent_id, principal_user_id, granted_by_user_id, org_id, reason, max_depth, expires_at, revoked_at, created_at, updated_at
FROM delegations
WHERE ($1::uuid IS NULL OR agent_id = $1::uuid)
  AND ($2::uuid IS NULL OR principal_user_id = $2::uuid)
  AND ($3::bool OR revoked_at IS NULL)
  AND ($4::uuid[] IS NULL
       OR org_id = ANY ($4::uuid[])
       OR principal_user_id = $5::uuid)
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type ListDelegationsParams struct {
	AgentID         sql.NullString
	PrincipalUserID sql.NullString
	IncludeRevoked  bool
	OrgIds          []string
	SelfUserID      sql.NullString
	RowOffset       int32
	RowLimit        int32
}

// Every filter is optional and written as "unset or matching". Two of them are
// not filters the caller asked for:
//
//	org_ids     the organizations the caller holds a live grant in. NULL is a
//	            platform grant, which answers about every organization.
//	self_user_id the caller themselves, always visible whatever org_ids says -
//	            a person must be able to see, and therefore revoke, what they
//	            granted, even if the agent lives somewhere they cannot
//	            otherwise read.
//
// `revoked_at` is filtered here because revoking is a write: the revision
// counter moves and caches drop. `expires_at` is deliberately *not* filtered -
// an expiry is the one change nobody writes, so a query that hid lapsed rows
// would let a warm cache keep serving one.
func (q *Queries) ListDelegations(ctx context.Context, arg ListDelegationsParams) ([]*Delegation, error) {
	rows, err := q.db.QueryContext(ctx, listDelegations,
		arg.AgentID,
		arg.PrincipalUserID,
		arg.IncludeRevoked,
		pq.Array(arg.OrgIds),
		arg.SelfUserID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Delegation{}
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.PrincipalUserID,
			&i.GrantedByUserID,
			&i.OrgID,
			&i.Reason,
			&i.MaxDepth,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDelegation = `-- name: RevokeDelegation :execrows
UPDATE delegations
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

// Matching only a live row is what makes a repeated revocation not a second
// event: the second statement changes nothing and the caller is told so.
func (q *Queries) RevokeDelegation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeDelegation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectDelegation = `-- name: SelectDelegation :one
SELECT id, agent_id, principal_user_id, granted_by_user_id, org_id, reason, max_depth, expires_at, revoked_at, created_at, updated_at
FROM delegations
WHERE id = $1
LIMIT 1
`

func (q *Queries) SelectDelegation(ctx context.Context, id string) (*Delegation, error) {
	row := q.db.QueryRowContext(ctx, selectDelegation, id)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.PrincipalUserID,
		&i.GrantedByUserID,
		&i.OrgID,
		&i.Reason,
		&i.MaxDepth,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const selectDelegationPermissions = `-- name: SelectDelegationPermissions :many
SELECT delegation_id, permission_id, created_at, updated_at
FROM delegation_permissions
WHERE delegation_id = $1
ORDER BY permission_id
`

func (q *Queries) SelectDelegationPermissions(ctx context.Context, delegationID string) ([]*DelegationPermission, error) {
	rows, err := q.db.QueryContext(ctx, selectDelegationPermissions, delegationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DelegationPermission{}
	for rows.Next() {
		var i DelegationPermission
		if err := rows.Scan(
			&i.DelegationID,
			&i.PermissionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
