// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group.sql

package sqlc

import (
	"context"
)

const createGroup = `-- name: CreateGroup :exec
INSERT INTO "groups" (id,
                      name,
                      status,
                      description,
                      created_at,
                      updated_at)
VALUES ($1,
        $2,
        $3,
        $4,
        now(),
        now())
`

type CreateGroupParams struct {
	ID          string
	Name        string
	Status      string
	Description string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Description,
	)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE
FROM "groups"
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const selectGroupById = `-- name: SelectGroupById :one
SELECT id, name, description, status, created_at, updated_at
FROM "groups"
WHERE id = $1 LIMIT 1
`

func (q *Queries) SelectGroupById(ctx context.Context, id string) (*Group, error) {
	row := q.db.QueryRowContext(ctx, selectGroupById, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const selectGroupForUpdate = `-- name: SelectGroupForUpdate :one
SELECT id, name, description, status, created_at, updated_at
FROM "groups"
WHERE id = $1 LIMIT 1 FOR
UPDATE
`

func (q *Queries) SelectGroupForUpdate(ctx context.Context, id string) (*Group, error) {
	row := q.db.QueryRowContext(ctx, selectGroupForUpdate, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE "groups"
SET name        = $1,
    description = $2,
    status      = $3,
    updated_at  = now()
WHERE id = $4
`

type UpdateGroupParams struct {
	Name        string
	Description string
	Status      string
	ID          string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	return err
}
