// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type AccessRequest struct {
	ID              string
	RequesterUserID string
	SubjectUserID   string
	GroupID         string
	Reason          string
	RequestedUntil  sql.NullTime
	Status          string
	Origin          string
	SessionID       sql.NullString
	DecidedByUserID sql.NullString
	DecidedAt       sql.NullTime
	DecisionComment string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AuditLog struct {
	ID          string
	ActorUserID string
	Channel     string
	AiSessionID sql.NullString
	Resource    string
	Action      string
	TargetID    string
	Arguments   json.RawMessage
	Succeeded   bool
	Error       string
	Client      string
	CreatedAt   time.Time
	ApprovalID  sql.NullString
}

type ChatMessage struct {
	ID        string
	SessionID string
	Role      string
	Content   string
	CreatedAt time.Time
}

type ChatSession struct {
	ID         string
	UserID     string
	Title      string
	CreatedAt  time.Time
	TokensUsed int64
}

type ChatToolProposal struct {
	ID           string
	SessionID    string
	ToolName     string
	Arguments    json.RawMessage
	Continuation []byte
	Status       string
	CreatedAt    time.Time
	DecidedAt    sql.NullTime
}

type Group struct {
	ID          string
	Name        string
	Description string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GroupRole struct {
	GroupID   string
	RoleID    string
	ExpiresAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Permission struct {
	ID          string
	Verb        string
	ResourceID  string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RbacRevision struct {
	ID        int16
	Revision  int64
	UpdatedAt time.Time
}

type Resource struct {
	ID           string
	ParentID     sql.NullString
	Name         string
	Identifier   string
	Type         string
	Path         sql.NullString
	Component    sql.NullString
	DisplayOrder sql.NullInt32
	Description  string
	Metadata     pqtype.NullRawMessage
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Role struct {
	ID          string
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RolePermission struct {
	RoleID       string
	PermissionID string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ServiceAccount struct {
	ID              string
	UserID          string
	Name            string
	Description     string
	ClientID        string
	KeycloakID      string
	CreatedByUserID string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type User struct {
	ID        string
	Username  string
	Email     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserGroup struct {
	UserID    string
	GroupID   string
	ExpiresAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}
