// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package sqlc

import (
	"context"
)

const createPermission = `-- name: CreatePermission :exec
INSERT INTO permissions (id,
                         verb,
                         resource_id,
                         description,
                         created_at,
                         updated_at)
VALUES ($1,
        $2,
        $3,
        $4,
        now(),
        now())
`

type CreatePermissionParams struct {
	ID          string
	Verb        string
	ResourceID  string
	Description string
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createPermission,
		arg.ID,
		arg.Verb,
		arg.ResourceID,
		arg.Description,
	)
	return err
}

const deletePermissions = `-- name: DeletePermissions :exec
DELETE
FROM "permissions"
WHERE id = $1
`

func (q *Queries) DeletePermissions(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePermissions, id)
	return err
}

const selectPermissionById = `-- name: SelectPermissionById :one
SELECT id, verb, resource_id, description, created_at, updated_at
FROM permissions
WHERE id = $1 LIMIT 1
`

func (q *Queries) SelectPermissionById(ctx context.Context, id string) (*Permission, error) {
	row := q.db.QueryRowContext(ctx, selectPermissionById, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Verb,
		&i.ResourceID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const selectPermissionByResourceId = `-- name: SelectPermissionByResourceId :many
SELECT id, verb, resource_id, description, created_at, updated_at
FROM permissions
WHERE resource_id = $1
`

func (q *Queries) SelectPermissionByResourceId(ctx context.Context, resourceID string) ([]*Permission, error) {
	rows, err := q.db.QueryContext(ctx, selectPermissionByResourceId, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Verb,
			&i.ResourceID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPermissionForUpdate = `-- name: SelectPermissionForUpdate :one
SELECT id, verb, resource_id, description, created_at, updated_at
FROM permissions
WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) SelectPermissionForUpdate(ctx context.Context, id string) (*Permission, error) {
	row := q.db.QueryRowContext(ctx, selectPermissionForUpdate, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Verb,
		&i.ResourceID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE permissions
SET verb        = $1,
    resource_id = $2,
    description = $3,
    updated_at  = now()
WHERE id = $4
`

type UpdatePermissionParams struct {
	Verb        string
	ResourceID  string
	Description string
	ID          string
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, updatePermission,
		arg.Verb,
		arg.ResourceID,
		arg.Description,
		arg.ID,
	)
	return err
}
