// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Adding rather than setting, so two streams on one session both count.
	AddChatSessionTokens(ctx context.Context, arg AddChatSessionTokensParams) error
	AddPermissionToDelegation(ctx context.Context, arg AddPermissionToDelegationParams) error
	AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error
	CountAccessRequests(ctx context.Context, arg CountAccessRequestsParams) (int64, error)
	// An agent with children cannot be removed: deleting it would leave their
	// credentials working with nothing in hub recording them. The count is asked
	// before anything is touched rather than left to the foreign key to refuse
	// half-way through the delete.
	CountAgentChildren(ctx context.Context, parentAgentID string) (int64, error)
	CountAgents(ctx context.Context, arg CountAgentsParams) (int64, error)
	CountDelegations(ctx context.Context, arg CountDelegationsParams) (int64, error)
	CountServiceAccounts(ctx context.Context) (int64, error)
	CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) error
	CreateAgent(ctx context.Context, arg CreateAgentParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (*AuditLog, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (*ChatMessage, error)
	CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (*ChatSession, error)
	CreateChatToolProposal(ctx context.Context, arg CreateChatToolProposalParams) (*ChatToolProposal, error)
	CreateDelegation(ctx context.Context, arg CreateDelegationParams) error
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	CreateGroupRole(ctx context.Context, arg CreateGroupRoleParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error
	CreatePermission(ctx context.Context, arg CreatePermissionParams) error
	CreateResource(ctx context.Context, arg CreateResourceParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) error
	// Deciding is conditional on the request still being pending, so two decisions
	// racing cannot both grant the access: the second updates no row.
	DecideAccessRequest(ctx context.Context, arg DecideAccessRequestParams) (*AccessRequest, error)
	// Deciding is conditional on the proposal still being pending, so two decisions
	// racing cannot both run the change: the second updates no row.
	DecideChatToolProposal(ctx context.Context, arg DecideChatToolProposalParams) (*ChatToolProposal, error)
	DeleteAgent(ctx context.Context, id string) error
	DeleteChatSession(ctx context.Context, arg DeleteChatSessionParams) error
	DeleteGroup(ctx context.Context, id string) error
	DeleteGroupAllRole(ctx context.Context, groupID string) error
	DeleteGroupRole(ctx context.Context, arg DeleteGroupRoleParams) error
	DeleteOrganization(ctx context.Context, id string) error
	DeletePermissions(ctx context.Context, id string) error
	DeleteResource(ctx context.Context, id string) error
	DeleteRole(ctx context.Context, id string) error
	DeleteRoleAllPermission(ctx context.Context, roleID string) error
	DeleteServiceAccount(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserAllGroup(ctx context.Context, userID string) error
	DeleteUserGroup(ctx context.Context, arg DeleteUserGroupParams) error
	IsPermissionInRole(ctx context.Context, arg IsPermissionInRoleParams) (bool, error)
	IsUserInGroup(ctx context.Context, arg IsUserInGroupParams) (bool, error)
	// Every filter is optional and written as "unset or matching", so one query
	// serves the approver's queue ("pending"), the requester's own list ("mine")
	// and a group's history without three near-identical statements.
	// Newest first: a queue is read from the top.
	ListAccessRequests(ctx context.Context, arg ListAccessRequestsParams) ([]*AccessRequest, error)
	// Every filter is optional and written as "unset or matching". org_ids is the
	// caller's reach rather than a filter they asked for: NULL is a platform grant,
	// which answers about every organization, and any other value is the set they
	// hold a live grant in. Listing every agent would tell one customer which
	// agents another runs.
	ListAgents(ctx context.Context, arg ListAgentsParams) ([]*Agent, error)
	// Every filter is optional and written as "unset or matching". Two of them are
	// not filters the caller asked for:
	//
	//   org_ids     the organizations the caller holds a live grant in. NULL is a
	//               platform grant, which answers about every organization.
	//   self_user_id the caller themselves, always visible whatever org_ids says -
	//               a person must be able to see, and therefore revoke, what they
	//               granted, even if the agent lives somewhere they cannot
	//               otherwise read.
	//
	// `revoked_at` is filtered here because revoking is a write: the revision
	// counter moves and caches drop. `expires_at` is deliberately *not* filtered -
	// an expiry is the one change nobody writes, so a query that hid lapsed rows
	// would let a warm cache keep serving one.
	ListDelegations(ctx context.Context, arg ListDelegationsParams) ([]*Delegation, error)
	// The listing is not filtered. A deployment has a handful of machines, not a
	// directory of them, and "who created it" is a column to read rather than a
	// question to ask the database.
	ListServiceAccounts(ctx context.Context, arg ListServiceAccountsParams) ([]*ServiceAccount, error)
	RecordAgentSecretRotation(ctx context.Context, id string) error
	RemoveAllUsersFromGroup(ctx context.Context, groupID string) error
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	// Matching only a live row is what makes a repeated revocation not a second
	// event: the second statement changes nothing and the caller is told so.
	RevokeDelegation(ctx context.Context, id string) (int64, error)
	SelectAccessPaths(ctx context.Context) ([]*SelectAccessPathsRow, error)
	SelectAccessRequest(ctx context.Context, id string) (*AccessRequest, error)
	SelectAgent(ctx context.Context, id string) (*Agent, error)
	SelectChatMessagesBySessionId(ctx context.Context, arg SelectChatMessagesBySessionIdParams) ([]*ChatMessage, error)
	// Scoping every lookup by user_id keeps a session private to its owner even if
	// a caller reaches the repository without going through the use case, which is
	// where the check used to live alone. A session belonging to someone else
	// returns no row, so it is indistinguishable from one that does not exist.
	SelectChatSessionById(ctx context.Context, arg SelectChatSessionByIdParams) (*ChatSession, error)
	SelectChatSessionsByUserId(ctx context.Context, userID string) ([]*ChatSession, error)
	// Scoped by user_id through the session, for the same reason every other chat
	// query is: a proposal belonging to someone else is absent, not refused.
	SelectChatToolProposalById(ctx context.Context, arg SelectChatToolProposalByIdParams) (*ChatToolProposal, error)
	SelectDelegation(ctx context.Context, id string) (*Delegation, error)
	SelectDelegationPermissions(ctx context.Context, delegationID string) ([]*DelegationPermission, error)
	SelectGroupById(ctx context.Context, id string) (*Group, error)
	SelectGroupForUpdate(ctx context.Context, id string) (*Group, error)
	SelectGroupRoleByGroupId(ctx context.Context, groupID string) ([]*GroupRole, error)
	SelectMemberships(ctx context.Context) ([]*SelectMembershipsRow, error)
	SelectOrganization(ctx context.Context, id string) (*Organization, error)
	// The slug is how an operator and a URL name a tenant, so it is looked up as
	// often as the id is.
	SelectOrganizationBySlug(ctx context.Context, slug string) (*Organization, error)
	SelectPermissionById(ctx context.Context, id string) (*Permission, error)
	SelectPermissionByResourceId(ctx context.Context, resourceID string) ([]*Permission, error)
	SelectPermissionForUpdate(ctx context.Context, id string) (*Permission, error)
	SelectRbacRevision(ctx context.Context) (int64, error)
	SelectResourceById(ctx context.Context, id string) (*Resource, error)
	SelectResourceByIdentifier(ctx context.Context, identifier string) (*Resource, error)
	SelectResourceForUpdate(ctx context.Context, id string) (*Resource, error)
	SelectRoleById(ctx context.Context, id string) (*Role, error)
	SelectRoleForUpdate(ctx context.Context, id string) (*Role, error)
	SelectRolePermissionByRoleId(ctx context.Context, roleID string) ([]*RolePermission, error)
	SelectServiceAccount(ctx context.Context, id string) (*ServiceAccount, error)
	SelectUserAccessPaths(ctx context.Context, id string) ([]*SelectUserAccessPathsRow, error)
	// The expiry is not filtered here on purpose: see the note on expires_at in
	// the user_groups and group_roles migrations.
	//
	// Both edges of the route are returned rather than LEAST() of them, so that
	// "the route expires with whichever edge expires first" is stated once, in Go,
	// where it is under test - and so that a NULL keeps meaning "never" rather than
	// depending on how LEAST treats it.
	//
	// The organization is returned for the same reason and read the same way. It is
	// the group's, because the group is the edge that joins a user to a permission,
	// and it is returned rather than compared here so that the policy cache holds a
	// set of policies rather than the answer to one question.
	SelectUserAuthorizedPolices(ctx context.Context, id string) ([]*SelectUserAuthorizedPolicesRow, error)
	SelectUserById(ctx context.Context, id string) (*User, error)
	SelectUserForUpdate(ctx context.Context, id string) (*User, error)
	SelectUserGroupByGroupId(ctx context.Context, groupID string) ([]*UserGroup, error)
	SelectUserGroupByUserId(ctx context.Context, userID string) ([]*UserGroup, error)
	// The organizations a user can reach, by way of the groups they are in. There
	// is no membership table of its own: belonging to an organization is having a
	// group in it, which is the same edge an authorization decision reads.
	SelectUserOrganizations(ctx context.Context, userID string) ([]*Organization, error)
	// org_id is not updatable. Moving a group to another organization would carry
	// every member's access across a tenant boundary in one statement, which is a
	// migration rather than an edit.
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) error
	// The kind is not updatable. Changing an organization from BUSINESS to PLATFORM
	// would hand it every tenant's data in one statement, and changing it the other
	// way would revoke every administrator; neither is an edit, both are migrations.
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error
	UpdateResource(ctx context.Context, arg UpdateResourceParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
