// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac_revision.sql

package sqlc

import (
	"context"
)

const selectRbacRevision = `-- name: SelectRbacRevision :one
SELECT revision
FROM rbac_revisions
WHERE id = 1
`

func (q *Queries) SelectRbacRevision(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectRbacRevision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
