// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createResource = `-- name: CreateResource :exec
INSERT INTO resources (id,
                       parent_id,
                       name,
                       identifier,
                       type,
                       path,
                       component,
                       display_order,
                       description,
                       metadata,
                       status,
                       created_at,
                       updated_at)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        now(),
        now())
`

type CreateResourceParams struct {
	ID           string
	ParentID     string
	Name         string
	Identifier   string
	Type         string
	Path         sql.NullString
	Component    sql.NullString
	DisplayOrder sql.NullInt32
	Description  string
	Metadata     pqtype.NullRawMessage
	Status       string
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) error {
	_, err := q.db.ExecContext(ctx, createResource,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Identifier,
		arg.Type,
		arg.Path,
		arg.Component,
		arg.DisplayOrder,
		arg.Description,
		arg.Metadata,
		arg.Status,
	)
	return err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE
FROM "resources"
WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const selectResourceById = `-- name: SelectResourceById :one
SELECT id, parent_id, name, identifier, type, path, component, display_order, description, metadata, status, created_at, updated_at
FROM resources
WHERE id = $1 LIMIT 1
`

func (q *Queries) SelectResourceById(ctx context.Context, id string) (*Resource, error) {
	row := q.db.QueryRowContext(ctx, selectResourceById, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Identifier,
		&i.Type,
		&i.Path,
		&i.Component,
		&i.DisplayOrder,
		&i.Description,
		&i.Metadata,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const selectResourceByIdentifier = `-- name: SelectResourceByIdentifier :one
SELECT id, parent_id, name, identifier, type, path, component, display_order, description, metadata, status, created_at, updated_at
FROM resources
WHERE identifier = $1 LIMIT 1
`

func (q *Queries) SelectResourceByIdentifier(ctx context.Context, identifier string) (*Resource, error) {
	row := q.db.QueryRowContext(ctx, selectResourceByIdentifier, identifier)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Identifier,
		&i.Type,
		&i.Path,
		&i.Component,
		&i.DisplayOrder,
		&i.Description,
		&i.Metadata,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const selectResourceForUpdate = `-- name: SelectResourceForUpdate :one
SELECT id, parent_id, name, identifier, type, path, component, display_order, description, metadata, status, created_at, updated_at
FROM resources
WHERE id = $1 LIMIT 1 FOR
UPDATE
`

func (q *Queries) SelectResourceForUpdate(ctx context.Context, id string) (*Resource, error) {
	row := q.db.QueryRowContext(ctx, selectResourceForUpdate, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Identifier,
		&i.Type,
		&i.Path,
		&i.Component,
		&i.DisplayOrder,
		&i.Description,
		&i.Metadata,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateResource = `-- name: UpdateResource :exec
UPDATE resources
SET parent_id     = $1,
    name          = $2,
    identifier    = $3,
    type          = $4,
    path          = $5,
    component     = $6,
    display_order = $7,
    description   = $8,
    metadata      = $9,
    status        = $10,
    updated_at    = now()
WHERE id = $11
`

type UpdateResourceParams struct {
	ParentID     string
	Name         string
	Identifier   string
	Type         string
	Path         sql.NullString
	Component    sql.NullString
	DisplayOrder sql.NullInt32
	Description  string
	Metadata     pqtype.NullRawMessage
	Status       string
	ID           string
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) error {
	_, err := q.db.ExecContext(ctx, updateResource,
		arg.ParentID,
		arg.Name,
		arg.Identifier,
		arg.Type,
		arg.Path,
		arg.Component,
		arg.DisplayOrder,
		arg.Description,
		arg.Metadata,
		arg.Status,
		arg.ID,
	)
	return err
}
