// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: serviceaccount.sql

package sqlc

import (
	"context"
)

const countServiceAccounts = `-- name: CountServiceAccounts :one
SELECT count(*)
FROM service_accounts
`

func (q *Queries) CountServiceAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServiceAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceAccount = `-- name: CreateServiceAccount :exec
INSERT INTO service_accounts (id,
                              user_id,
                              name,
                              description,
                              client_id,
                              keycloak_id,
                              created_by_user_id,
                              created_at,
                              updated_at)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        now(),
        now())
`

type CreateServiceAccountParams struct {
	ID              string
	UserID          string
	Name            string
	Description     string
	ClientID        string
	KeycloakID      string
	CreatedByUserID string
}

func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) error {
	_, err := q.db.ExecContext(ctx, createServiceAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ClientID,
		arg.KeycloakID,
		arg.CreatedByUserID,
	)
	return err
}

const deleteServiceAccount = `-- name: DeleteServiceAccount :exec
DELETE
FROM service_accounts
WHERE id = $1
`

func (q *Queries) DeleteServiceAccount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteServiceAccount, id)
	return err
}

const listServiceAccounts = `-- name: ListServiceAccounts :many
SELECT id, user_id, name, description, client_id, keycloak_id, created_by_user_id, created_at, updated_at
FROM service_accounts
ORDER BY name
LIMIT $2 OFFSET $1
`

type ListServiceAccountsParams struct {
	RowOffset int32
	RowLimit  int32
}

// The listing is not filtered. A deployment has a handful of machines, not a
// directory of them, and "who created it" is a column to read rather than a
// question to ask the database.
func (q *Queries) ListServiceAccounts(ctx context.Context, arg ListServiceAccountsParams) ([]*ServiceAccount, error) {
	rows, err := q.db.QueryContext(ctx, listServiceAccounts, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ServiceAccount{}
	for rows.Next() {
		var i ServiceAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.KeycloakID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectServiceAccount = `-- name: SelectServiceAccount :one
SELECT id, user_id, name, description, client_id, keycloak_id, created_by_user_id, created_at, updated_at
FROM service_accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) SelectServiceAccount(ctx context.Context, id string) (*ServiceAccount, error) {
	row := q.db.QueryRowContext(ctx, selectServiceAccount, id)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.KeycloakID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
