apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

secretGenerator:
  - name: hub-secret
    behavior: replace
    namespace: hub
    envs:
      - hub-secret.env
  - name: keycloak-secret
    behavior: replace
    namespace: keycloak
    options:
      disableNameSuffixHash: true
    envs:
      - keycloak-secret.env
  - name: postgres-secret
    behavior: replace
    namespace: postgresql
    options:
      disableNameSuffixHash: true
    envs:
      - postgres-secret.env
  - name: postgres-secret
    behavior: replace
    namespace: hub
    options:
      disableNameSuffixHash: true
    envs:
      - postgres-secret.env

patches:
  - target:
      kind: Service
      name: hub
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
  - target:
      kind: Service
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
