// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/resource/v1/service.proto

package v1

import (
	_ "github.com/linzhengen/hub/v1/server/pb/hub/annotations/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_system_resource_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceResponse) Reset() {
	*x = GetResourceResponse{}
	mi := &file_system_resource_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceResponse) ProtoMessage() {}

func (x *GetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ListResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,3,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	ResourceName  string                 `protobuf:"bytes,4,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=system.resource.v1.Status" json:"status,omitempty"`
	ResourceType  Type                   `protobuf:"varint,6,opt,name=resource_type,json=resourceType,proto3,enum=system.resource.v1.Type" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceRequest) Reset() {
	*x = ListResourceRequest{}
	mi := &file_system_resource_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceRequest) ProtoMessage() {}

func (x *ListResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceRequest.ProtoReflect.Descriptor instead.
func (*ListResourceRequest) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListResourceRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListResourceRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListResourceRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *ListResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ListResourceRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ListResourceRequest) GetResourceType() Type {
	if x != nil {
		return x.ResourceType
	}
	return Type_TYPE_UNSPECIFIED
}

type ListResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceResponse) Reset() {
	*x = ListResourceResponse{}
	mi := &file_system_resource_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceResponse) ProtoMessage() {}

func (x *ListResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceResponse.ProtoReflect.Descriptor instead.
func (*ListResourceResponse) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListResourceResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListResourceResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListMenuResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,3,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	ResourceName  string                 `protobuf:"bytes,4,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=system.resource.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuResourceRequest) Reset() {
	*x = ListMenuResourceRequest{}
	mi := &file_system_resource_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuResourceRequest) ProtoMessage() {}

func (x *ListMenuResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuResourceRequest.ProtoReflect.Descriptor instead.
func (*ListMenuResourceRequest) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListMenuResourceRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMenuResourceRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMenuResourceRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *ListMenuResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ListMenuResourceRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type ListMenuResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuResourceResponse) Reset() {
	*x = ListMenuResourceResponse{}
	mi := &file_system_resource_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuResourceResponse) ProtoMessage() {}

func (x *ListMenuResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuResourceResponse.ProtoReflect.Descriptor instead.
func (*ListMenuResourceResponse) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListMenuResourceResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListMenuResourceResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Identifier    *Identifier            `protobuf:"bytes,4,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Type          Type                   `protobuf:"varint,5,opt,name=type,proto3,enum=system.resource.v1.Type" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Component     *string                `protobuf:"bytes,7,opt,name=component,proto3,oneof" json:"component,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,8,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	Description   *string                `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        Status                 `protobuf:"varint,11,opt,name=status,proto3,enum=system.resource.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_system_resource_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateResourceRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateResourceRequest) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *CreateResourceRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *CreateResourceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateResourceRequest) GetComponent() string {
	if x != nil && x.Component != nil {
		return *x.Component
	}
	return ""
}

func (x *CreateResourceRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *CreateResourceRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateResourceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateResourceRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type CreateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceResponse) Reset() {
	*x = CreateResourceResponse{}
	mi := &file_system_resource_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponse) ProtoMessage() {}

func (x *CreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceResponse) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type UpdateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Identifier    *Identifier            `protobuf:"bytes,4,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Type          Type                   `protobuf:"varint,5,opt,name=type,proto3,enum=system.resource.v1.Type" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Component     *string                `protobuf:"bytes,7,opt,name=component,proto3,oneof" json:"component,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,8,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	Description   *string                `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        Status                 `protobuf:"varint,11,opt,name=status,proto3,enum=system.resource.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceRequest) Reset() {
	*x = UpdateResourceRequest{}
	mi := &file_system_resource_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceRequest) ProtoMessage() {}

func (x *UpdateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateResourceRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *UpdateResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateResourceRequest) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *UpdateResourceRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *UpdateResourceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateResourceRequest) GetComponent() string {
	if x != nil && x.Component != nil {
		return *x.Component
	}
	return ""
}

func (x *UpdateResourceRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *UpdateResourceRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateResourceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateResourceRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type UpdateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceResponse) Reset() {
	*x = UpdateResourceResponse{}
	mi := &file_system_resource_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceResponse) ProtoMessage() {}

func (x *UpdateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceResponse.ProtoReflect.Descriptor instead.
func (*UpdateResourceResponse) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_system_resource_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_system_resource_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{11}
}

type CreateMenuResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Component     *string                `protobuf:"bytes,4,opt,name=component,proto3,oneof" json:"component,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,5,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        Status                 `protobuf:"varint,8,opt,name=status,proto3,enum=system.resource.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuResourceRequest) Reset() {
	*x = CreateMenuResourceRequest{}
	mi := &file_system_resource_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuResourceRequest) ProtoMessage() {}

func (x *CreateMenuResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuResourceRequest) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateMenuResourceRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateMenuResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuResourceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateMenuResourceRequest) GetComponent() string {
	if x != nil && x.Component != nil {
		return *x.Component
	}
	return ""
}

func (x *CreateMenuResourceRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *CreateMenuResourceRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateMenuResourceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateMenuResourceRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type CreateMenuResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuResourceResponse) Reset() {
	*x = CreateMenuResourceResponse{}
	mi := &file_system_resource_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuResourceResponse) ProtoMessage() {}

func (x *CreateMenuResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateMenuResourceResponse) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateMenuResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type UpdateMenuResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Component     *string                `protobuf:"bytes,5,opt,name=component,proto3,oneof" json:"component,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,6,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	Description   *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        Status                 `protobuf:"varint,9,opt,name=status,proto3,enum=system.resource.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuResourceRequest) Reset() {
	*x = UpdateMenuResourceRequest{}
	mi := &file_system_resource_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuResourceRequest) ProtoMessage() {}

func (x *UpdateMenuResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuResourceRequest) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateMenuResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMenuResourceRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *UpdateMenuResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMenuResourceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateMenuResourceRequest) GetComponent() string {
	if x != nil && x.Component != nil {
		return *x.Component
	}
	return ""
}

func (x *UpdateMenuResourceRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *UpdateMenuResourceRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateMenuResourceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateMenuResourceRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type UpdateMenuResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuResourceResponse) Reset() {
	*x = UpdateMenuResourceResponse{}
	mi := &file_system_resource_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuResourceResponse) ProtoMessage() {}

func (x *UpdateMenuResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_resource_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuResourceResponse.ProtoReflect.Descriptor instead.
func (*UpdateMenuResourceResponse) Descriptor() ([]byte, []int) {
	return file_system_resource_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateMenuResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_system_resource_v1_service_proto protoreflect.FileDescriptor

const file_system_resource_v1_service_proto_rawDesc = "" +
	"\n" +
	" system/resource/v1/service.proto\x12\x12system.resource.v1\x1a\x1cgoogle/api/annotations.proto\x1a$hub/annotations/v1/annotations.proto\x1a\x1esystem/resource/v1/model.proto\"$\n" +
	"\x12GetResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x13GetResourceResponse\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.system.resource.v1.ResourceR\bresource\"\xfe\x01\n" +
	"\x13ListResourceRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12!\n" +
	"\fresource_ids\x18\x03 \x03(\tR\vresourceIds\x12#\n" +
	"\rresource_name\x18\x04 \x01(\tR\fresourceName\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.system.resource.v1.StatusR\x06status\x12=\n" +
	"\rresource_type\x18\x06 \x01(\x0e2\x18.system.resource.v1.TypeR\fresourceType\"h\n" +
	"\x14ListResourceResponse\x12:\n" +
	"\tresources\x18\x01 \x03(\v2\x1c.system.resource.v1.ResourceR\tresources\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xc3\x01\n" +
	"\x17ListMenuResourceRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12!\n" +
	"\fresource_ids\x18\x03 \x03(\tR\vresourceIds\x12#\n" +
	"\rresource_name\x18\x04 \x01(\tR\fresourceName\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.system.resource.v1.StatusR\x06status\"l\n" +
	"\x18ListMenuResourceResponse\x12:\n" +
	"\tresources\x18\x01 \x03(\v2\x1c.system.resource.v1.ResourceR\tresources\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x9d\x04\n" +
	"\x15CreateResourceRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12>\n" +
	"\n" +
	"identifier\x18\x04 \x01(\v2\x1e.system.resource.v1.IdentifierR\n" +
	"identifier\x12,\n" +
	"\x04type\x18\x05 \x01(\x0e2\x18.system.resource.v1.TypeR\x04type\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12!\n" +
	"\tcomponent\x18\a \x01(\tH\x00R\tcomponent\x88\x01\x01\x12#\n" +
	"\rdisplay_order\x18\b \x01(\x05R\fdisplayOrder\x12%\n" +
	"\vdescription\x18\t \x01(\tH\x01R\vdescription\x88\x01\x01\x12S\n" +
	"\bmetadata\x18\n" +
	" \x03(\v27.system.resource.v1.CreateResourceRequest.MetadataEntryR\bmetadata\x122\n" +
	"\x06status\x18\v \x01(\x0e2\x1a.system.resource.v1.StatusR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_componentB\x0e\n" +
	"\f_description\"R\n" +
	"\x16CreateResourceResponse\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.system.resource.v1.ResourceR\bresource\"\xad\x04\n" +
	"\x15UpdateResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12>\n" +
	"\n" +
	"identifier\x18\x04 \x01(\v2\x1e.system.resource.v1.IdentifierR\n" +
	"identifier\x12,\n" +
	"\x04type\x18\x05 \x01(\x0e2\x18.system.resource.v1.TypeR\x04type\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12!\n" +
	"\tcomponent\x18\a \x01(\tH\x00R\tcomponent\x88\x01\x01\x12#\n" +
	"\rdisplay_order\x18\b \x01(\x05R\fdisplayOrder\x12%\n" +
	"\vdescription\x18\t \x01(\tH\x01R\vdescription\x88\x01\x01\x12S\n" +
	"\bmetadata\x18\n" +
	" \x03(\v27.system.resource.v1.UpdateResourceRequest.MetadataEntryR\bmetadata\x122\n" +
	"\x06status\x18\v \x01(\x0e2\x1a.system.resource.v1.StatusR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_componentB\x0e\n" +
	"\f_description\"R\n" +
	"\x16UpdateResourceResponse\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.system.resource.v1.ResourceR\bresource\"'\n" +
	"\x15DeleteResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteResourceResponse\"\xb7\x03\n" +
	"\x19CreateMenuResourceRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12!\n" +
	"\tcomponent\x18\x04 \x01(\tH\x00R\tcomponent\x88\x01\x01\x12#\n" +
	"\rdisplay_order\x18\x05 \x01(\x05R\fdisplayOrder\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x01R\vdescription\x88\x01\x01\x12W\n" +
	"\bmetadata\x18\a \x03(\v2;.system.resource.v1.CreateMenuResourceRequest.MetadataEntryR\bmetadata\x122\n" +
	"\x06status\x18\b \x01(\x0e2\x1a.system.resource.v1.StatusR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_componentB\x0e\n" +
	"\f_description\"V\n" +
	"\x1aCreateMenuResourceResponse\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.system.resource.v1.ResourceR\bresource\"\xc7\x03\n" +
	"\x19UpdateMenuResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12!\n" +
	"\tcomponent\x18\x05 \x01(\tH\x00R\tcomponent\x88\x01\x01\x12#\n" +
	"\rdisplay_order\x18\x06 \x01(\x05R\fdisplayOrder\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x01R\vdescription\x88\x01\x01\x12W\n" +
	"\bmetadata\x18\b \x03(\v2;.system.resource.v1.UpdateMenuResourceRequest.MetadataEntryR\bmetadata\x122\n" +
	"\x06status\x18\t \x01(\x0e2\x1a.system.resource.v1.StatusR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_componentB\x0e\n" +
	"\f_description\"V\n" +
	"\x1aUpdateMenuResourceResponse\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.system.resource.v1.ResourceR\bresource2\xa4\v\n" +
	"\x0fResourceService\x12\xa0\x01\n" +
	"\vGetResource\x12&.system.resource.v1.GetResourceRequest\x1a'.system.resource.v1.GetResourceResponse\"@\x8a\xa6\x1d\x1e\"\x1cGet a single resource by id.\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/resources/{id}\x12\xc2\x01\n" +
	"\fListResource\x12'.system.resource.v1.ListResourceRequest\x1a(.system.resource.v1.ListResourceResponse\"_\x8a\xa6\x1dB\"@List resources, optionally filtered by id, name, status or type.\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/resources\x12\xc3\x01\n" +
	"\x0eCreateResource\x12).system.resource.v1.CreateResourceRequest\x1a*.system.resource.v1.CreateResourceResponse\"Z\x8a\xa6\x1d:\"8Create a resource (an API or menu entry RBAC can guard).\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/resources\x12\xa2\x01\n" +
	"\x0eUpdateResource\x12).system.resource.v1.UpdateResourceRequest\x1a*.system.resource.v1.UpdateResourceResponse\"9\x8a\xa6\x1d\x14\"\x12Update a resource.\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/v1/resources/{id}\x12\x9f\x01\n" +
	"\x0eDeleteResource\x12).system.resource.v1.DeleteResourceRequest\x1a*.system.resource.v1.DeleteResourceResponse\"6\x8a\xa6\x1d\x14\"\x12Delete a resource.\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/resources/{id}\x12\xa8\x01\n" +
	"\x10ListMenuResource\x12+.system.resource.v1.ListMenuResourceRequest\x1a,.system.resource.v1.ListMenuResourceResponse\"9\x8a\xa6\x1d\x16\"\x14List menu resources.\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/resources/menus\x12\xb4\x01\n" +
	"\x12CreateMenuResource\x12-.system.resource.v1.CreateMenuResourceRequest\x1a..system.resource.v1.CreateMenuResourceResponse\"?\x8a\xa6\x1d\x19\"\x17Create a menu resource.\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/resources/menus\x12\xb9\x01\n" +
	"\x12UpdateMenuResource\x12-.system.resource.v1.UpdateMenuResourceRequest\x1a..system.resource.v1.UpdateMenuResourceResponse\"D\x8a\xa6\x1d\x19\"\x17Update a menu resource.\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/api/v1/resources/{id}/menusB;Z9github.com/linzhengen/hub/v1/server/pb/system/resource/v1b\x06proto3"

var (
	file_system_resource_v1_service_proto_rawDescOnce sync.Once
	file_system_resource_v1_service_proto_rawDescData []byte
)

func file_system_resource_v1_service_proto_rawDescGZIP() []byte {
	file_system_resource_v1_service_proto_rawDescOnce.Do(func() {
		file_system_resource_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_resource_v1_service_proto_rawDesc), len(file_system_resource_v1_service_proto_rawDesc)))
	})
	return file_system_resource_v1_service_proto_rawDescData
}

var file_system_resource_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_system_resource_v1_service_proto_goTypes = []any{
	(*GetResourceRequest)(nil),         // 0: system.resource.v1.GetResourceRequest
	(*GetResourceResponse)(nil),        // 1: system.resource.v1.GetResourceResponse
	(*ListResourceRequest)(nil),        // 2: system.resource.v1.ListResourceRequest
	(*ListResourceResponse)(nil),       // 3: system.resource.v1.ListResourceResponse
	(*ListMenuResourceRequest)(nil),    // 4: system.resource.v1.ListMenuResourceRequest
	(*ListMenuResourceResponse)(nil),   // 5: system.resource.v1.ListMenuResourceResponse
	(*CreateResourceRequest)(nil),      // 6: system.resource.v1.CreateResourceRequest
	(*CreateResourceResponse)(nil),     // 7: system.resource.v1.CreateResourceResponse
	(*UpdateResourceRequest)(nil),      // 8: system.resource.v1.UpdateResourceRequest
	(*UpdateResourceResponse)(nil),     // 9: system.resource.v1.UpdateResourceResponse
	(*DeleteResourceRequest)(nil),      // 10: system.resource.v1.DeleteResourceRequest
	(*DeleteResourceResponse)(nil),     // 11: system.resource.v1.DeleteResourceResponse
	(*CreateMenuResourceRequest)(nil),  // 12: system.resource.v1.CreateMenuResourceRequest
	(*CreateMenuResourceResponse)(nil), // 13: system.resource.v1.CreateMenuResourceResponse
	(*UpdateMenuResourceRequest)(nil),  // 14: system.resource.v1.UpdateMenuResourceRequest
	(*UpdateMenuResourceResponse)(nil), // 15: system.resource.v1.UpdateMenuResourceResponse
	nil,                                // 16: system.resource.v1.CreateResourceRequest.MetadataEntry
	nil,                                // 17: system.resource.v1.UpdateResourceRequest.MetadataEntry
	nil,                                // 18: system.resource.v1.CreateMenuResourceRequest.MetadataEntry
	nil,                                // 19: system.resource.v1.UpdateMenuResourceRequest.MetadataEntry
	(*Resource)(nil),                   // 20: system.resource.v1.Resource
	(Status)(0),                        // 21: system.resource.v1.Status
	(Type)(0),                          // 22: system.resource.v1.Type
	(*Identifier)(nil),                 // 23: system.resource.v1.Identifier
}
var file_system_resource_v1_service_proto_depIdxs = []int32{
	20, // 0: system.resource.v1.GetResourceResponse.resource:type_name -> system.resource.v1.Resource
	21, // 1: system.resource.v1.ListResourceRequest.status:type_name -> system.resource.v1.Status
	22, // 2: system.resource.v1.ListResourceRequest.resource_type:type_name -> system.resource.v1.Type
	20, // 3: system.resource.v1.ListResourceResponse.resources:type_name -> system.resource.v1.Resource
	21, // 4: system.resource.v1.ListMenuResourceRequest.status:type_name -> system.resource.v1.Status
	20, // 5: system.resource.v1.ListMenuResourceResponse.resources:type_name -> system.resource.v1.Resource
	23, // 6: system.resource.v1.CreateResourceRequest.identifier:type_name -> system.resource.v1.Identifier
	22, // 7: system.resource.v1.CreateResourceRequest.type:type_name -> system.resource.v1.Type
	16, // 8: system.resource.v1.CreateResourceRequest.metadata:type_name -> system.resource.v1.CreateResourceRequest.MetadataEntry
	21, // 9: system.resource.v1.CreateResourceRequest.status:type_name -> system.resource.v1.Status
	20, // 10: system.resource.v1.CreateResourceResponse.resource:type_name -> system.resource.v1.Resource
	23, // 11: system.resource.v1.UpdateResourceRequest.identifier:type_name -> system.resource.v1.Identifier
	22, // 12: system.resource.v1.UpdateResourceRequest.type:type_name -> system.resource.v1.Type
	17, // 13: system.resource.v1.UpdateResourceRequest.metadata:type_name -> system.resource.v1.UpdateResourceRequest.MetadataEntry
	21, // 14: system.resource.v1.UpdateResourceRequest.status:type_name -> system.resource.v1.Status
	20, // 15: system.resource.v1.UpdateResourceResponse.resource:type_name -> system.resource.v1.Resource
	18, // 16: system.resource.v1.CreateMenuResourceRequest.metadata:type_name -> system.resource.v1.CreateMenuResourceRequest.MetadataEntry
	21, // 17: system.resource.v1.CreateMenuResourceRequest.status:type_name -> system.resource.v1.Status
	20, // 18: system.resource.v1.CreateMenuResourceResponse.resource:type_name -> system.resource.v1.Resource
	19, // 19: system.resource.v1.UpdateMenuResourceRequest.metadata:type_name -> system.resource.v1.UpdateMenuResourceRequest.MetadataEntry
	21, // 20: system.resource.v1.UpdateMenuResourceRequest.status:type_name -> system.resource.v1.Status
	20, // 21: system.resource.v1.UpdateMenuResourceResponse.resource:type_name -> system.resource.v1.Resource
	0,  // 22: system.resource.v1.ResourceService.GetResource:input_type -> system.resource.v1.GetResourceRequest
	2,  // 23: system.resource.v1.ResourceService.ListResource:input_type -> system.resource.v1.ListResourceRequest
	6,  // 24: system.resource.v1.ResourceService.CreateResource:input_type -> system.resource.v1.CreateResourceRequest
	8,  // 25: system.resource.v1.ResourceService.UpdateResource:input_type -> system.resource.v1.UpdateResourceRequest
	10, // 26: system.resource.v1.ResourceService.DeleteResource:input_type -> system.resource.v1.DeleteResourceRequest
	4,  // 27: system.resource.v1.ResourceService.ListMenuResource:input_type -> system.resource.v1.ListMenuResourceRequest
	12, // 28: system.resource.v1.ResourceService.CreateMenuResource:input_type -> system.resource.v1.CreateMenuResourceRequest
	14, // 29: system.resource.v1.ResourceService.UpdateMenuResource:input_type -> system.resource.v1.UpdateMenuResourceRequest
	1,  // 30: system.resource.v1.ResourceService.GetResource:output_type -> system.resource.v1.GetResourceResponse
	3,  // 31: system.resource.v1.ResourceService.ListResource:output_type -> system.resource.v1.ListResourceResponse
	7,  // 32: system.resource.v1.ResourceService.CreateResource:output_type -> system.resource.v1.CreateResourceResponse
	9,  // 33: system.resource.v1.ResourceService.UpdateResource:output_type -> system.resource.v1.UpdateResourceResponse
	11, // 34: system.resource.v1.ResourceService.DeleteResource:output_type -> system.resource.v1.DeleteResourceResponse
	5,  // 35: system.resource.v1.ResourceService.ListMenuResource:output_type -> system.resource.v1.ListMenuResourceResponse
	13, // 36: system.resource.v1.ResourceService.CreateMenuResource:output_type -> system.resource.v1.CreateMenuResourceResponse
	15, // 37: system.resource.v1.ResourceService.UpdateMenuResource:output_type -> system.resource.v1.UpdateMenuResourceResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_system_resource_v1_service_proto_init() }
func file_system_resource_v1_service_proto_init() {
	if File_system_resource_v1_service_proto != nil {
		return
	}
	file_system_resource_v1_model_proto_init()
	file_system_resource_v1_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_system_resource_v1_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_system_resource_v1_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_system_resource_v1_service_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_resource_v1_service_proto_rawDesc), len(file_system_resource_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_resource_v1_service_proto_goTypes,
		DependencyIndexes: file_system_resource_v1_service_proto_depIdxs,
		MessageInfos:      file_system_resource_v1_service_proto_msgTypes,
	}.Build()
	File_system_resource_v1_service_proto = out.File
	file_system_resource_v1_service_proto_goTypes = nil
	file_system_resource_v1_service_proto_depIdxs = nil
}
