/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GroupService_ListGroup"];
        put?: never;
        post: operations["GroupService_CreateGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GroupService_GetGroup"];
        put: operations["GroupService_UpdateGroup"];
        post?: never;
        delete: operations["GroupService_DeleteGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/roles/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GroupService_AddRolesToGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/roles/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GroupService_RemoveRolesFromGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/users/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GroupService_AddUsersToGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/users/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GroupService_RemoveUsersFromGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GroupServiceAddRolesToGroupBody: {
            /**
             * Format: date-time
             * @description When the grant lapses. Leave it unset to grant for good, which is what
             *     every grant made before this field existed did.
             *
             *     It applies to each id in this request, since one call is one decision:
             *     "give them these three until Friday". A grant with a different term is a
             *     different decision, so it is a different call.
             */
            expiresAt?: string;
            roleIds?: string[];
        };
        GroupServiceAddUsersToGroupBody: {
            /**
             * Format: date-time
             * @description When the grant lapses. Leave it unset to grant for good, which is what
             *     every grant made before this field existed did.
             *
             *     It applies to each id in this request, since one call is one decision:
             *     "give them these three until Friday". A grant with a different term is a
             *     different decision, so it is a different call.
             */
            expiresAt?: string;
            userIds?: string[];
        };
        GroupServiceRemoveRolesFromGroupBody: {
            roleIds?: string[];
        };
        GroupServiceRemoveUsersFromGroupBody: {
            userIds?: string[];
        };
        GroupServiceUpdateGroupBody: {
            description?: string;
            name?: string;
            status?: components["schemas"]["v1GroupStatus"];
        };
        googleRpcStatus: {
            /** Format: int32 */
            code?: number;
            details?: components["schemas"]["protobufAny"][];
            message?: string;
        };
        protobufAny: {
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        v1AddRolesToGroupResponse: {
            group?: components["schemas"]["v1Group"];
        };
        v1AddUsersToGroupResponse: {
            group?: components["schemas"]["v1Group"];
        };
        v1CreateGroupRequest: {
            description?: string;
            name?: string;
            /**
             * @description Which organization the group belongs to. Required: a group with no
             *     organization would be a route to a permission that no boundary contains.
             */
            orgId?: string;
            status?: components["schemas"]["v1GroupStatus"];
        };
        v1CreateGroupResponse: {
            group?: components["schemas"]["v1Group"];
        };
        v1DeleteGroupResponse: Record<string, never>;
        v1GetGroupResponse: {
            group?: components["schemas"]["v1Group"];
        };
        v1Group: {
            /** Format: date-time */
            createdAt?: string;
            description?: string;
            id?: string;
            name?: string;
            /**
             * @description The organization this group belongs to.
             *
             *     It is the group that carries the boundary, because the group is the only
             *     edge that joins a user to a permission: placing it here places every route
             *     through it. A group does not move between organizations - that would carry
             *     its members' access across a tenant boundary in one statement - so this is
             *     set at creation and never updated.
             */
            orgId?: string;
            roles?: components["schemas"]["v1RoleGrant"][];
            status?: components["schemas"]["v1GroupStatus"];
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @default STATUS_UNSPECIFIED
         * @enum {string}
         */
        v1GroupStatus: "STATUS_UNSPECIFIED" | "STATUS_ACTIVE" | "STATUS_INACTIVE";
        v1ListGroupResponse: {
            groups?: components["schemas"]["v1Group"][];
            /** Format: int64 */
            total?: string;
        };
        v1RemoveRolesFromGroupResponse: {
            group?: components["schemas"]["v1Group"];
        };
        v1RemoveUsersFromGroupResponse: {
            group?: components["schemas"]["v1Group"];
        };
        /** @description RoleGrant is one role the group holds, and when it stops holding it. */
        v1RoleGrant: {
            /**
             * Format: date-time
             * @description When the grant lapses, unset when it does not. A grant that ends on Friday
             *     and one that never ends are different things and must not read the same.
             */
            expiresAt?: string;
            roleId?: string;
        };
        v1UpdateGroupResponse: {
            group?: components["schemas"]["v1Group"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GroupService_ListGroup: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                groupIds?: string[];
                groupName?: string;
                status?: "STATUS_UNSPECIFIED" | "STATUS_ACTIVE" | "STATUS_INACTIVE";
                roleIds?: string[];
                /**
                 * @description Narrow to one organization. Absent lists every organization the caller can
                 *     reach, which is what every caller asked for before organizations existed.
                 *
                 *     optional, so the uuid rule is skipped when the filter is not used at all -
                 *     a bare `string` is validated even when it is empty, and every unfiltered
                 *     listing would be refused. Same as the other filters in this API.
                 */
                orgId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListGroupResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["googleRpcStatus"];
                };
            };
        };
    };
    GroupService_CreateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateGroupRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1CreateGroupResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["googleRpcStatus"];
                };
            };
        };
    };
    GroupService_GetGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetGroupResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["googleRpcStatus"];
                };
            };
        };
    };
    GroupService_UpdateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupServiceUpdateGroupBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1UpdateGroupResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["googleRpcStatus"];
                };
            };
        };
    };
    GroupService_DeleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteGroupResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["googleRpcStatus"];
                };
            };
        };
    };
    GroupService_AddRolesToGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupServiceAddRolesToGroupBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1AddRolesToGroupResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["googleRpcStatus"];
                };
            };
        };
    };
    GroupService_RemoveRolesFromGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupServiceRemoveRolesFromGroupBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1RemoveRolesFromGroupResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["googleRpcStatus"];
                };
            };
        };
    };
    GroupService_AddUsersToGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupServiceAddUsersToGroupBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1AddUsersToGroupResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["googleRpcStatus"];
                };
            };
        };
    };
    GroupService_RemoveUsersFromGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupServiceRemoveUsersFromGroupBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1RemoveUsersFromGroupResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["googleRpcStatus"];
                };
            };
        };
    };
}
