/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/access/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccessService_ExplainUserAccess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/principals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccessService_ListPrincipalsForOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        protobufAny: {
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        rpcStatus: {
            /** Format: int32 */
            code?: number;
            details?: components["schemas"]["protobufAny"][];
            message?: string;
        };
        /**
         * @description AccessPath is one route by which a user is allowed an operation: the group
         *     they belong to, the role that group holds, and the permission that role
         *     grants.
         *
         *     A user often holds the same access by more than one route. Every route is
         *     reported rather than the first one found, because revoking one of three is
         *     not a revocation, and noticing that is the reason to ask.
         */
        v1AccessPath: {
            action?: string;
            groupId?: string;
            groupName?: string;
            permissionId?: string;
            /**
             * @description The resource identifier and verb the permission itself names, patterns
             *     included: a route granted through `api.*` reports `api.*`, not the
             *     operation that was asked about. A wildcard grant is the thing most worth
             *     seeing here, so it is not resolved away.
             */
            resource?: string;
            roleId?: string;
            roleName?: string;
        };
        v1ExplainUserAccessResponse: {
            /**
             * @description Allowed is the answer the authorization interceptor would give the same
             *     question. It is exactly `paths` being non-empty, carried explicitly so a
             *     caller reading only this field cannot misread an empty list.
             */
            allowed?: boolean;
            paths?: components["schemas"]["v1AccessPath"][];
        };
        v1ListPrincipalsForOperationResponse: {
            principals?: components["schemas"]["v1Principal"][];
        };
        /** @description Principal is a user allowed an operation, with every route that allows it. */
        v1Principal: {
            paths?: components["schemas"]["v1AccessPath"][];
            userId?: string;
            username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AccessService_ExplainUserAccess: {
        parameters: {
            query?: {
                userId?: string;
                /**
                 * @description The resource and verb as the server enforces them - `api.user.v1.UserService`
                 *     and `ListUser` - not a REST path. `hub api describe <rpc>` prints the pair
                 *     for any operation.
                 */
                resource?: string;
                action?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ExplainUserAccessResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AccessService_ListPrincipalsForOperation: {
        parameters: {
            query?: {
                resource?: string;
                action?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListPrincipalsForOperationResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
}
