// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rolepermission.sql

package sqlc

import (
	"context"
)

const addPermissionToRole = `-- name: AddPermissionToRole :exec
INSERT INTO role_permissions (role_id,
                              permission_id,
                              created_at,
                              updated_at)
VALUES (?,
        ?,
        now(),
        now())
`

type AddPermissionToRoleParams struct {
	RoleID       string
	PermissionID string
}

func (q *Queries) AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error {
	_, err := q.db.ExecContext(ctx, addPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const deleteRoleAllPermission = `-- name: DeleteRoleAllPermission :exec
DELETE
FROM role_permissions
WHERE role_id = ?
`

func (q *Queries) DeleteRoleAllPermission(ctx context.Context, roleID string) error {
	_, err := q.db.ExecContext(ctx, deleteRoleAllPermission, roleID)
	return err
}

const isPermissionInRole = `-- name: IsPermissionInRole :one
SELECT EXISTS(SELECT 1 FROM role_permissions WHERE role_id = ? AND permission_id = ?)
`

type IsPermissionInRoleParams struct {
	RoleID       string
	PermissionID string
}

func (q *Queries) IsPermissionInRole(ctx context.Context, arg IsPermissionInRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isPermissionInRole, arg.RoleID, arg.PermissionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE
FROM role_permissions
WHERE role_id = ?
  AND permission_id = ?
`

type RemovePermissionFromRoleParams struct {
	RoleID       string
	PermissionID string
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.ExecContext(ctx, removePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const selectRolePermissionByRoleId = `-- name: SelectRolePermissionByRoleId :many
SELECT role_id, permission_id, created_at, updated_at
FROM role_permissions
WHERE role_id = ?
`

func (q *Queries) SelectRolePermissionByRoleId(ctx context.Context, roleID string) ([]*RolePermission, error) {
	rows, err := q.db.QueryContext(ctx, selectRolePermissionByRoleId, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.RoleID,
			&i.PermissionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
