// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usergroup.sql

package sqlc

import (
	"context"
)

const createUserGroup = `-- name: CreateUserGroup :exec
INSERT INTO user_groups (user_id,
                         group_id,
                         created_at,
                         updated_at)
VALUES (?,
        ?,
        now(),
        now())
`

type CreateUserGroupParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, createUserGroup, arg.UserID, arg.GroupID)
	return err
}

const deleteUserAllGroup = `-- name: DeleteUserAllGroup :exec
DELETE
FROM user_groups
WHERE user_id = ?
`

func (q *Queries) DeleteUserAllGroup(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserAllGroup, userID)
	return err
}

const deleteUserGroup = `-- name: DeleteUserGroup :exec
DELETE
FROM user_groups
WHERE user_id = ?
  AND group_id = ?
`

type DeleteUserGroupParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) DeleteUserGroup(ctx context.Context, arg DeleteUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserGroup, arg.UserID, arg.GroupID)
	return err
}

const isUserInGroup = `-- name: IsUserInGroup :one
SELECT EXISTS(SELECT 1 FROM user_groups WHERE user_id = ? AND group_id = ?)
`

type IsUserInGroupParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) IsUserInGroup(ctx context.Context, arg IsUserInGroupParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserInGroup, arg.UserID, arg.GroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeAllUsersFromGroup = `-- name: RemoveAllUsersFromGroup :exec
DELETE FROM user_groups WHERE group_id = ?
`

func (q *Queries) RemoveAllUsersFromGroup(ctx context.Context, groupID string) error {
	_, err := q.db.ExecContext(ctx, removeAllUsersFromGroup, groupID)
	return err
}

const selectUserGroupByGroupId = `-- name: SelectUserGroupByGroupId :many
SELECT user_id, group_id, created_at, updated_at
FROM user_groups
WHERE group_id = ?
`

func (q *Queries) SelectUserGroupByGroupId(ctx context.Context, groupID string) ([]*UserGroup, error) {
	rows, err := q.db.QueryContext(ctx, selectUserGroupByGroupId, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserGroup{}
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserGroupByUserId = `-- name: SelectUserGroupByUserId :many
SELECT user_id, group_id, created_at, updated_at
FROM user_groups
WHERE user_id = ?
`

func (q *Queries) SelectUserGroupByUserId(ctx context.Context, userID string) ([]*UserGroup, error) {
	rows, err := q.db.QueryContext(ctx, selectUserGroupByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserGroup{}
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
