// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/delegation/v1/model.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Delegation is one agent's permission to act on one person's behalf.
//
// It is a row rather than a token, so it can be revoked now: the change moves
// the RBAC revision counter and every policy cache drops what it holds within a
// second. A token would have a residual lifetime instead.
//
// The effective authority of an agent acting under a delegation is the agent's
// own grants intersected with the principal's grants intersected with this
// delegation, and the intersection is taken when the decision is made rather
// than when the row is written.
type Delegation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The agent that may act.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Whose authority is lent. Only this person can create the delegation, so an
	// agent cannot be handed a stranger's authority by a third party.
	PrincipalUserId string `protobuf:"bytes,3,opt,name=principal_user_id,json=principalUserId,proto3" json:"principal_user_id,omitempty"`
	// Who wrote the row. Today always the principal.
	GrantedByUserId string `protobuf:"bytes,4,opt,name=granted_by_user_id,json=grantedByUserId,proto3" json:"granted_by_user_id,omitempty"`
	// The organization the delegation is answerable in, taken from the agent.
	OrgId string `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Why it exists, in the words of the person who agreed to it.
	Reason string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// What the delegation carries: a subset of the permissions the principal
	// holds. Never empty - there is no "everything" delegation.
	PermissionIds []string `protobuf:"bytes,7,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	// How many agents may stand in the chain. 1 is the agent named here and no
	// further.
	MaxDepth uint32 `protobuf:"varint,8,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	// When the delegation stops. Absent means it does not, which the API does not
	// offer: an endless delegation is the exception.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// When it was withdrawn, absent while live. The row is kept rather than
	// deleted, because "this agent could act for me until Tuesday" is what an
	// investigation needs afterwards.
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delegation) Reset() {
	*x = Delegation{}
	mi := &file_system_delegation_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delegation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delegation) ProtoMessage() {}

func (x *Delegation) ProtoReflect() protoreflect.Message {
	mi := &file_system_delegation_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delegation.ProtoReflect.Descriptor instead.
func (*Delegation) Descriptor() ([]byte, []int) {
	return file_system_delegation_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *Delegation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Delegation) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Delegation) GetPrincipalUserId() string {
	if x != nil {
		return x.PrincipalUserId
	}
	return ""
}

func (x *Delegation) GetGrantedByUserId() string {
	if x != nil {
		return x.GrantedByUserId
	}
	return ""
}

func (x *Delegation) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Delegation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Delegation) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

func (x *Delegation) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *Delegation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Delegation) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *Delegation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Delegation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_system_delegation_v1_model_proto protoreflect.FileDescriptor

const file_system_delegation_v1_model_proto_rawDesc = "" +
	"\n" +
	" system/delegation/v1/model.proto\x12\x14system.delegation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x03\n" +
	"\n" +
	"Delegation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12*\n" +
	"\x11principal_user_id\x18\x03 \x01(\tR\x0fprincipalUserId\x12+\n" +
	"\x12granted_by_user_id\x18\x04 \x01(\tR\x0fgrantedByUserId\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12%\n" +
	"\x0epermission_ids\x18\a \x03(\tR\rpermissionIds\x12\x1b\n" +
	"\tmax_depth\x18\b \x01(\rR\bmaxDepth\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"revoked_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB:Z8github.com/linzhengen/hub/server/pb/system/delegation/v1b\x06proto3"

var (
	file_system_delegation_v1_model_proto_rawDescOnce sync.Once
	file_system_delegation_v1_model_proto_rawDescData []byte
)

func file_system_delegation_v1_model_proto_rawDescGZIP() []byte {
	file_system_delegation_v1_model_proto_rawDescOnce.Do(func() {
		file_system_delegation_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_delegation_v1_model_proto_rawDesc), len(file_system_delegation_v1_model_proto_rawDesc)))
	})
	return file_system_delegation_v1_model_proto_rawDescData
}

var file_system_delegation_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_system_delegation_v1_model_proto_goTypes = []any{
	(*Delegation)(nil),            // 0: system.delegation.v1.Delegation
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_system_delegation_v1_model_proto_depIdxs = []int32{
	1, // 0: system.delegation.v1.Delegation.expires_at:type_name -> google.protobuf.Timestamp
	1, // 1: system.delegation.v1.Delegation.revoked_at:type_name -> google.protobuf.Timestamp
	1, // 2: system.delegation.v1.Delegation.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: system.delegation.v1.Delegation.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_system_delegation_v1_model_proto_init() }
func file_system_delegation_v1_model_proto_init() {
	if File_system_delegation_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_delegation_v1_model_proto_rawDesc), len(file_system_delegation_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_delegation_v1_model_proto_goTypes,
		DependencyIndexes: file_system_delegation_v1_model_proto_depIdxs,
		MessageInfos:      file_system_delegation_v1_model_proto_msgTypes,
	}.Build()
	File_system_delegation_v1_model_proto = out.File
	file_system_delegation_v1_model_proto_goTypes = nil
	file_system_delegation_v1_model_proto_depIdxs = nil
}
