// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: system/delegation/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DelegationService_CreateDelegation_FullMethodName = "/system.delegation.v1.DelegationService/CreateDelegation"
	DelegationService_ListDelegations_FullMethodName  = "/system.delegation.v1.DelegationService/ListDelegations"
	DelegationService_RevokeDelegation_FullMethodName = "/system.delegation.v1.DelegationService/RevokeDelegation"
)

// DelegationServiceClient is the client API for DelegationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DelegationService records which agent may act on whose behalf.
//
// Creating and revoking a delegation change who can do what, so neither is
// reachable by the assistant. A delegation is the one thing that lets a machine
// borrow a person's authority; a model talked into writing one by text
// somebody else wrote would be exactly the escalation the approval flow exists
// to prevent.
type DelegationServiceClient interface {
	CreateDelegation(ctx context.Context, in *CreateDelegationRequest, opts ...grpc.CallOption) (*CreateDelegationResponse, error)
	ListDelegations(ctx context.Context, in *ListDelegationsRequest, opts ...grpc.CallOption) (*ListDelegationsResponse, error)
	RevokeDelegation(ctx context.Context, in *RevokeDelegationRequest, opts ...grpc.CallOption) (*RevokeDelegationResponse, error)
}

type delegationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDelegationServiceClient(cc grpc.ClientConnInterface) DelegationServiceClient {
	return &delegationServiceClient{cc}
}

func (c *delegationServiceClient) CreateDelegation(ctx context.Context, in *CreateDelegationRequest, opts ...grpc.CallOption) (*CreateDelegationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDelegationResponse)
	err := c.cc.Invoke(ctx, DelegationService_CreateDelegation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delegationServiceClient) ListDelegations(ctx context.Context, in *ListDelegationsRequest, opts ...grpc.CallOption) (*ListDelegationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDelegationsResponse)
	err := c.cc.Invoke(ctx, DelegationService_ListDelegations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delegationServiceClient) RevokeDelegation(ctx context.Context, in *RevokeDelegationRequest, opts ...grpc.CallOption) (*RevokeDelegationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeDelegationResponse)
	err := c.cc.Invoke(ctx, DelegationService_RevokeDelegation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelegationServiceServer is the server API for DelegationService service.
// All implementations should embed UnimplementedDelegationServiceServer
// for forward compatibility.
//
// DelegationService records which agent may act on whose behalf.
//
// Creating and revoking a delegation change who can do what, so neither is
// reachable by the assistant. A delegation is the one thing that lets a machine
// borrow a person's authority; a model talked into writing one by text
// somebody else wrote would be exactly the escalation the approval flow exists
// to prevent.
type DelegationServiceServer interface {
	CreateDelegation(context.Context, *CreateDelegationRequest) (*CreateDelegationResponse, error)
	ListDelegations(context.Context, *ListDelegationsRequest) (*ListDelegationsResponse, error)
	RevokeDelegation(context.Context, *RevokeDelegationRequest) (*RevokeDelegationResponse, error)
}

// UnimplementedDelegationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDelegationServiceServer struct{}

func (UnimplementedDelegationServiceServer) CreateDelegation(context.Context, *CreateDelegationRequest) (*CreateDelegationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDelegation not implemented")
}
func (UnimplementedDelegationServiceServer) ListDelegations(context.Context, *ListDelegationsRequest) (*ListDelegationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDelegations not implemented")
}
func (UnimplementedDelegationServiceServer) RevokeDelegation(context.Context, *RevokeDelegationRequest) (*RevokeDelegationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeDelegation not implemented")
}
func (UnimplementedDelegationServiceServer) testEmbeddedByValue() {}

// UnsafeDelegationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DelegationServiceServer will
// result in compilation errors.
type UnsafeDelegationServiceServer interface {
	mustEmbedUnimplementedDelegationServiceServer()
}

func RegisterDelegationServiceServer(s grpc.ServiceRegistrar, srv DelegationServiceServer) {
	// If the following call panics, it indicates UnimplementedDelegationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DelegationService_ServiceDesc, srv)
}

func _DelegationService_CreateDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegationServiceServer).CreateDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DelegationService_CreateDelegation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegationServiceServer).CreateDelegation(ctx, req.(*CreateDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DelegationService_ListDelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDelegationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegationServiceServer).ListDelegations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DelegationService_ListDelegations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegationServiceServer).ListDelegations(ctx, req.(*ListDelegationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DelegationService_RevokeDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegationServiceServer).RevokeDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DelegationService_RevokeDelegation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegationServiceServer).RevokeDelegation(ctx, req.(*RevokeDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DelegationService_ServiceDesc is the grpc.ServiceDesc for DelegationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DelegationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.delegation.v1.DelegationService",
	HandlerType: (*DelegationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDelegation",
			Handler:    _DelegationService_CreateDelegation_Handler,
		},
		{
			MethodName: "ListDelegations",
			Handler:    _DelegationService_ListDelegations_Handler,
		},
		{
			MethodName: "RevokeDelegation",
			Handler:    _DelegationService_RevokeDelegation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system/delegation/v1/service.proto",
}
