// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/audit/v1/model.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Channel is the route a recorded change arrived by: CHANNEL_API is the user
// calling the API themselves (the console, the hub CLI, or a direct request),
// and CHANNEL_AI_CHAT is the assistant calling it while answering them, with
// session_id saying in which conversation.
//
// The per-value comments this would normally carry are left out on purpose: the
// OpenAPI generator renders them into a description that the web client's
// schema generator cannot parse.
type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_CHANNEL_API         Channel = 1
	Channel_CHANNEL_AI_CHAT     Channel = 2
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_API",
		2: "CHANNEL_AI_CHAT",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_API":         1,
		"CHANNEL_AI_CHAT":     2,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_system_audit_v1_model_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_system_audit_v1_model_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_system_audit_v1_model_proto_rawDescGZIP(), []int{0}
}

// AuditLog is one recorded attempt to change the authorization graph.
//
// The actor is always a person. A change the assistant made is recorded against
// the user it was answering, with channel telling them apart.
type AuditLog struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActorUserId string                 `protobuf:"bytes,2,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	Channel     Channel                `protobuf:"varint,3,opt,name=channel,proto3,enum=system.audit.v1.Channel" json:"channel,omitempty"`
	// The chat session the assistant was answering in. Empty for every other
	// channel.
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The RBAC resource and verb of the operation, so a record reads the same way
	// a permission does.
	Resource string `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	Action   string `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	// The entity that was changed, when the operation names one.
	TargetId string `protobuf:"bytes,7,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// The request as it arrived, as JSON, with secrets removed.
	Arguments string `protobuf:"bytes,8,opt,name=arguments,proto3" json:"arguments,omitempty"`
	// False for an attempt that was refused or failed. Those are recorded too.
	Succeeded bool   `protobuf:"varint,9,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Error     string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	// What the caller said it was - a user agent. Unverified.
	Client        string                 `protobuf:"bytes,11,opt,name=client,proto3" json:"client,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_system_audit_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_system_audit_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_system_audit_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLog) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *AuditLog) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *AuditLog) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuditLog) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLog) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AuditLog) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *AuditLog) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

func (x *AuditLog) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuditLog) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *AuditLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_system_audit_v1_model_proto protoreflect.FileDescriptor

const file_system_audit_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x1bsystem/audit/v1/model.proto\x12\x0fsystem.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x03\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\ractor_user_id\x18\x02 \x01(\tR\vactorUserId\x122\n" +
	"\achannel\x18\x03 \x01(\x0e2\x18.system.audit.v1.ChannelR\achannel\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bresource\x18\x05 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1b\n" +
	"\ttarget_id\x18\a \x01(\tR\btargetId\x12\x1c\n" +
	"\targuments\x18\b \x01(\tR\targuments\x12\x1c\n" +
	"\tsucceeded\x18\t \x01(\bR\tsucceeded\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12\x16\n" +
	"\x06client\x18\v \x01(\tR\x06client\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*H\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCHANNEL_API\x10\x01\x12\x13\n" +
	"\x0fCHANNEL_AI_CHAT\x10\x02B5Z3github.com/linzhengen/hub/server/pb/system/audit/v1b\x06proto3"

var (
	file_system_audit_v1_model_proto_rawDescOnce sync.Once
	file_system_audit_v1_model_proto_rawDescData []byte
)

func file_system_audit_v1_model_proto_rawDescGZIP() []byte {
	file_system_audit_v1_model_proto_rawDescOnce.Do(func() {
		file_system_audit_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_audit_v1_model_proto_rawDesc), len(file_system_audit_v1_model_proto_rawDesc)))
	})
	return file_system_audit_v1_model_proto_rawDescData
}

var file_system_audit_v1_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_system_audit_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_system_audit_v1_model_proto_goTypes = []any{
	(Channel)(0),                  // 0: system.audit.v1.Channel
	(*AuditLog)(nil),              // 1: system.audit.v1.AuditLog
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_system_audit_v1_model_proto_depIdxs = []int32{
	0, // 0: system.audit.v1.AuditLog.channel:type_name -> system.audit.v1.Channel
	2, // 1: system.audit.v1.AuditLog.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_system_audit_v1_model_proto_init() }
func file_system_audit_v1_model_proto_init() {
	if File_system_audit_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_audit_v1_model_proto_rawDesc), len(file_system_audit_v1_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_audit_v1_model_proto_goTypes,
		DependencyIndexes: file_system_audit_v1_model_proto_depIdxs,
		EnumInfos:         file_system_audit_v1_model_proto_enumTypes,
		MessageInfos:      file_system_audit_v1_model_proto_msgTypes,
	}.Build()
	File_system_audit_v1_model_proto = out.File
	file_system_audit_v1_model_proto_goTypes = nil
	file_system_audit_v1_model_proto_depIdxs = nil
}
