// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/audit/v1/service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/linzhengen/hub/server/pb/hub/annotations/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAuditLogRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Limit  uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// The person responsible for the change. Optional so that the uuid rule is
	// skipped when the filter is not used, rather than rejecting every unfiltered
	// listing.
	ActorUserId *string `protobuf:"bytes,3,opt,name=actor_user_id,json=actorUserId,proto3,oneof" json:"actor_user_id,omitempty"`
	// The RBAC resource, e.g. "api.system.group.v1.GroupService".
	Resource string `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	// The rpc name, e.g. "AddRolesToGroup".
	Action string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	// The entity that was changed.
	TargetId string  `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Channel  Channel `protobuf:"varint,7,opt,name=channel,proto3,enum=system.audit.v1.Channel" json:"channel,omitempty"`
	// Bounds on when the change was recorded. Either may be left unset.
	Since         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=since,proto3" json:"since,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogRequest) Reset() {
	*x = ListAuditLogRequest{}
	mi := &file_system_audit_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogRequest) ProtoMessage() {}

func (x *ListAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_audit_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_system_audit_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListAuditLogRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuditLogRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAuditLogRequest) GetActorUserId() string {
	if x != nil && x.ActorUserId != nil {
		return *x.ActorUserId
	}
	return ""
}

func (x *ListAuditLogRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ListAuditLogRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListAuditLogRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ListAuditLogRequest) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ListAuditLogRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListAuditLogRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type ListAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditLogs     []*AuditLog            `protobuf:"bytes,1,rep,name=audit_logs,json=auditLogs,proto3" json:"audit_logs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogResponse) Reset() {
	*x = ListAuditLogResponse{}
	mi := &file_system_audit_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogResponse) ProtoMessage() {}

func (x *ListAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_audit_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogResponse.ProtoReflect.Descriptor instead.
func (*ListAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_system_audit_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuditLogResponse) GetAuditLogs() []*AuditLog {
	if x != nil {
		return x.AuditLogs
	}
	return nil
}

func (x *ListAuditLogResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_system_audit_v1_service_proto protoreflect.FileDescriptor

const file_system_audit_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dsystem/audit/v1/service.proto\x12\x0fsystem.audit.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$hub/annotations/v1/annotations.proto\x1a\x1bsystem/audit/v1/model.proto\"\x98\x03\n" +
	"\x13ListAuditLogRequest\x12\x1e\n" +
	"\x05limit\x18\x01 \x01(\rB\b\xbaH\x05*\x03\x18\xc8\x01R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x121\n" +
	"\ractor_user_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\vactorUserId\x88\x01\x01\x12$\n" +
	"\bresource\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\bresource\x12\x1f\n" +
	"\x06action\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x18@R\x06action\x12%\n" +
	"\ttarget_id\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\btargetId\x122\n" +
	"\achannel\x18\a \x01(\x0e2\x18.system.audit.v1.ChannelR\achannel\x120\n" +
	"\x05since\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x05untilB\x10\n" +
	"\x0e_actor_user_id\"f\n" +
	"\x14ListAuditLogResponse\x128\n" +
	"\n" +
	"audit_logs\x18\x01 \x03(\v2\x19.system.audit.v1.AuditLogR\tauditLogs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xe5\x01\n" +
	"\fAuditService\x12\xd4\x01\n" +
	"\fListAuditLog\x12$.system.audit.v1.ListAuditLogRequest\x1a%.system.audit.v1.ListAuditLogResponse\"w\x8a\xa6\x1dY\"WList recorded changes to users, groups, roles, permissions and resources, newest first.\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/audit-logsB5Z3github.com/linzhengen/hub/server/pb/system/audit/v1b\x06proto3"

var (
	file_system_audit_v1_service_proto_rawDescOnce sync.Once
	file_system_audit_v1_service_proto_rawDescData []byte
)

func file_system_audit_v1_service_proto_rawDescGZIP() []byte {
	file_system_audit_v1_service_proto_rawDescOnce.Do(func() {
		file_system_audit_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_audit_v1_service_proto_rawDesc), len(file_system_audit_v1_service_proto_rawDesc)))
	})
	return file_system_audit_v1_service_proto_rawDescData
}

var file_system_audit_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_system_audit_v1_service_proto_goTypes = []any{
	(*ListAuditLogRequest)(nil),   // 0: system.audit.v1.ListAuditLogRequest
	(*ListAuditLogResponse)(nil),  // 1: system.audit.v1.ListAuditLogResponse
	(Channel)(0),                  // 2: system.audit.v1.Channel
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*AuditLog)(nil),              // 4: system.audit.v1.AuditLog
}
var file_system_audit_v1_service_proto_depIdxs = []int32{
	2, // 0: system.audit.v1.ListAuditLogRequest.channel:type_name -> system.audit.v1.Channel
	3, // 1: system.audit.v1.ListAuditLogRequest.since:type_name -> google.protobuf.Timestamp
	3, // 2: system.audit.v1.ListAuditLogRequest.until:type_name -> google.protobuf.Timestamp
	4, // 3: system.audit.v1.ListAuditLogResponse.audit_logs:type_name -> system.audit.v1.AuditLog
	0, // 4: system.audit.v1.AuditService.ListAuditLog:input_type -> system.audit.v1.ListAuditLogRequest
	1, // 5: system.audit.v1.AuditService.ListAuditLog:output_type -> system.audit.v1.ListAuditLogResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_system_audit_v1_service_proto_init() }
func file_system_audit_v1_service_proto_init() {
	if File_system_audit_v1_service_proto != nil {
		return
	}
	file_system_audit_v1_model_proto_init()
	file_system_audit_v1_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_audit_v1_service_proto_rawDesc), len(file_system_audit_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_audit_v1_service_proto_goTypes,
		DependencyIndexes: file_system_audit_v1_service_proto_depIdxs,
		MessageInfos:      file_system_audit_v1_service_proto_msgTypes,
	}.Build()
	File_system_audit_v1_service_proto = out.File
	file_system_audit_v1_service_proto_goTypes = nil
	file_system_audit_v1_service_proto_depIdxs = nil
}
