// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hub/annotations/v1/annotations.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MethodRule carries everything the platform needs to know about an RPC beyond
// its request and response types: how RBAC treats it and how it is described to
// humans and agents.
//
// Before this option existed the authorization interceptor derived both facts
// from the gRPC method string and kept its list of unauthenticated methods in a
// Go `switch`, so a new public endpoint meant editing the interceptor. Keeping
// the rule next to the rpc makes the proto the single source of truth for the
// server, the CLI and the generated agent documentation alike.
type MethodRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Skips the RBAC enforcement step. The caller must still be authenticated:
	// public means "any signed-in user", not "anonymous".
	Public bool `protobuf:"varint,1,opt,name=public,proto3" json:"public,omitempty"`
	// Resource identifier to enforce on. Defaults to `api.<proto package>.<Service>`,
	// which is what `resource-import` registers, so it only needs setting when an
	// rpc guards something other than its own service.
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Action (verb) to enforce on. Defaults to the rpc name.
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// One-line description of what the rpc does. Surfaced by `hub api list`,
	// `hub api describe` and the generated agent skill reference, so write it for
	// a reader who has never seen the proto.
	Summary       string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodRule) Reset() {
	*x = MethodRule{}
	mi := &file_hub_annotations_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodRule) ProtoMessage() {}

func (x *MethodRule) ProtoReflect() protoreflect.Message {
	mi := &file_hub_annotations_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodRule.ProtoReflect.Descriptor instead.
func (*MethodRule) Descriptor() ([]byte, []int) {
	return file_hub_annotations_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *MethodRule) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *MethodRule) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *MethodRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MethodRule) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var file_hub_annotations_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodRule)(nil),
		Field:         60001,
		Name:          "hub.annotations.v1.method_rule",
		Tag:           "bytes,60001,opt,name=method_rule",
		Filename:      "hub/annotations/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional hub.annotations.v1.MethodRule method_rule = 60001;
	E_MethodRule = &file_hub_annotations_v1_annotations_proto_extTypes[0]
)

var File_hub_annotations_v1_annotations_proto protoreflect.FileDescriptor

const file_hub_annotations_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"$hub/annotations/v1/annotations.proto\x12\x12hub.annotations.v1\x1a google/protobuf/descriptor.proto\"r\n" +
	"\n" +
	"MethodRule\x12\x16\n" +
	"\x06public\x18\x01 \x01(\bR\x06public\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary:a\n" +
	"\vmethod_rule\x12\x1e.google.protobuf.MethodOptions\x18\xe1\xd4\x03 \x01(\v2\x1e.hub.annotations.v1.MethodRuleR\n" +
	"methodRuleB8Z6github.com/linzhengen/hub/server/pb/hub/annotations/v1b\x06proto3"

var (
	file_hub_annotations_v1_annotations_proto_rawDescOnce sync.Once
	file_hub_annotations_v1_annotations_proto_rawDescData []byte
)

func file_hub_annotations_v1_annotations_proto_rawDescGZIP() []byte {
	file_hub_annotations_v1_annotations_proto_rawDescOnce.Do(func() {
		file_hub_annotations_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_annotations_v1_annotations_proto_rawDesc), len(file_hub_annotations_v1_annotations_proto_rawDesc)))
	})
	return file_hub_annotations_v1_annotations_proto_rawDescData
}

var file_hub_annotations_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hub_annotations_v1_annotations_proto_goTypes = []any{
	(*MethodRule)(nil),                 // 0: hub.annotations.v1.MethodRule
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_hub_annotations_v1_annotations_proto_depIdxs = []int32{
	1, // 0: hub.annotations.v1.method_rule:extendee -> google.protobuf.MethodOptions
	0, // 1: hub.annotations.v1.method_rule:type_name -> hub.annotations.v1.MethodRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hub_annotations_v1_annotations_proto_init() }
func file_hub_annotations_v1_annotations_proto_init() {
	if File_hub_annotations_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_annotations_v1_annotations_proto_rawDesc), len(file_hub_annotations_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_hub_annotations_v1_annotations_proto_goTypes,
		DependencyIndexes: file_hub_annotations_v1_annotations_proto_depIdxs,
		MessageInfos:      file_hub_annotations_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_hub_annotations_v1_annotations_proto_extTypes,
	}.Build()
	File_hub_annotations_v1_annotations_proto = out.File
	file_hub_annotations_v1_annotations_proto_goTypes = nil
	file_hub_annotations_v1_annotations_proto_depIdxs = nil
}
