apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: terraform-config-modules
    namespace: keycloak
    options:
      disableNameSuffixHash: true
    files:
      - main.tf
      - variables.tf
      - versions.tf
      - client_hub_api.tf
      - client_hub_web.tf
      - provider_github.tf
      - rbac.tf
      - outputs.tf
