// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/model.proto

package v1

import (
	v1 "github.com/linzhengen/hub/server/pb/system/resource/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User_Status int32

const (
	User_STATUS_UNSPECIFIED User_Status = 0
	User_STATUS_ACTIVE      User_Status = 1
	User_STATUS_INACTIVE    User_Status = 2
)

// Enum value maps for User_Status.
var (
	User_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
	}
	User_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
	}
)

func (x User_Status) Enum() *User_Status {
	p := new(User_Status)
	*p = x
	return p
}

func (x User_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_model_proto_enumTypes[0].Descriptor()
}

func (User_Status) Type() protoreflect.EnumType {
	return &file_user_v1_model_proto_enumTypes[0]
}

func (x User_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_Status.Descriptor instead.
func (User_Status) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_model_proto_rawDescGZIP(), []int{0, 0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Status        User_Status            `protobuf:"varint,4,opt,name=status,proto3,enum=user.v1.User_Status" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Groups        []*GroupMembership     `protobuf:"bytes,8,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetStatus() User_Status {
	if x != nil {
		return x.Status
	}
	return User_STATUS_UNSPECIFIED
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetGroups() []*GroupMembership {
	if x != nil {
		return x.Groups
	}
	return nil
}

// GroupMembership is one group the user is in, and when they leave it.
type GroupMembership struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// When the membership lapses, unset when it does not.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMembership) Reset() {
	*x = GroupMembership{}
	mi := &file_user_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembership) ProtoMessage() {}

func (x *GroupMembership) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembership.ProtoReflect.Descriptor instead.
func (*GroupMembership) Descriptor() ([]byte, []int) {
	return file_user_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMembership) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMembership) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type MenuMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Icon          string                 `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon,omitempty"`
	KeepAlive     bool                   `protobuf:"varint,2,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	Order         uint32                 `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Authority     string                 `protobuf:"bytes,5,opt,name=authority,proto3" json:"authority,omitempty"`
	Badge         string                 `protobuf:"bytes,6,opt,name=badge,proto3" json:"badge,omitempty"`
	HideInMenu    bool                   `protobuf:"varint,7,opt,name=hide_in_menu,json=hideInMenu,proto3" json:"hide_in_menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuMeta) Reset() {
	*x = MenuMeta{}
	mi := &file_user_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuMeta) ProtoMessage() {}

func (x *MenuMeta) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuMeta.ProtoReflect.Descriptor instead.
func (*MenuMeta) Descriptor() ([]byte, []int) {
	return file_user_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *MenuMeta) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuMeta) GetKeepAlive() bool {
	if x != nil {
		return x.KeepAlive
	}
	return false
}

func (x *MenuMeta) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *MenuMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MenuMeta) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MenuMeta) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *MenuMeta) GetHideInMenu() bool {
	if x != nil {
		return x.HideInMenu
	}
	return false
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`
	AuthCode      string                 `protobuf:"bytes,5,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	Type          v1.Type                `protobuf:"varint,6,opt,name=type,proto3,enum=system.resource.v1.Type" json:"type,omitempty"`
	Meta          *MenuMeta              `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	Children      []*Menu                `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_user_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_user_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Menu) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Menu) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Menu) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

func (x *Menu) GetType() v1.Type {
	if x != nil {
		return x.Type
	}
	return v1.Type(0)
}

func (x *Menu) GetMeta() *MenuMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Menu) GetChildren() []*Menu {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_user_v1_model_proto protoreflect.FileDescriptor

const file_user_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x13user/v1/model.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1esystem/resource/v1/model.proto\"\xee\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.user.v1.User.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x120\n" +
	"\x06groups\x18\b \x03(\v2\x18.user.v1.GroupMembershipR\x06groups\"H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02J\x04\b\a\x10\b\"{\n" +
	"\x0fGroupMembership\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12>\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_expires_at\"\xbf\x01\n" +
	"\bMenuMeta\x12\x12\n" +
	"\x04icon\x18\x01 \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\x02 \x01(\bR\tkeepAlive\x12\x14\n" +
	"\x05order\x18\x03 \x01(\rR\x05order\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1c\n" +
	"\tauthority\x18\x05 \x01(\tR\tauthority\x12\x14\n" +
	"\x05badge\x18\x06 \x01(\tR\x05badge\x12 \n" +
	"\fhide_in_menu\x18\a \x01(\bR\n" +
	"hideInMenu\"\x89\x02\n" +
	"\x04Menu\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\x04 \x01(\tR\tcomponent\x12\x1b\n" +
	"\tauth_code\x18\x05 \x01(\tR\bauthCode\x12,\n" +
	"\x04type\x18\x06 \x01(\x0e2\x18.system.resource.v1.TypeR\x04type\x12%\n" +
	"\x04meta\x18\a \x01(\v2\x11.user.v1.MenuMetaR\x04meta\x12)\n" +
	"\bchildren\x18\b \x03(\v2\r.user.v1.MenuR\bchildrenB-Z+github.com/linzhengen/hub/server/pb/user/v1b\x06proto3"

var (
	file_user_v1_model_proto_rawDescOnce sync.Once
	file_user_v1_model_proto_rawDescData []byte
)

func file_user_v1_model_proto_rawDescGZIP() []byte {
	file_user_v1_model_proto_rawDescOnce.Do(func() {
		file_user_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_model_proto_rawDesc), len(file_user_v1_model_proto_rawDesc)))
	})
	return file_user_v1_model_proto_rawDescData
}

var file_user_v1_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_v1_model_proto_goTypes = []any{
	(User_Status)(0),              // 0: user.v1.User.Status
	(*User)(nil),                  // 1: user.v1.User
	(*GroupMembership)(nil),       // 2: user.v1.GroupMembership
	(*MenuMeta)(nil),              // 3: user.v1.MenuMeta
	(*Menu)(nil),                  // 4: user.v1.Menu
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(v1.Type)(0),                  // 6: system.resource.v1.Type
}
var file_user_v1_model_proto_depIdxs = []int32{
	0, // 0: user.v1.User.status:type_name -> user.v1.User.Status
	5, // 1: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	2, // 3: user.v1.User.groups:type_name -> user.v1.GroupMembership
	5, // 4: user.v1.GroupMembership.expires_at:type_name -> google.protobuf.Timestamp
	6, // 5: user.v1.Menu.type:type_name -> system.resource.v1.Type
	3, // 6: user.v1.Menu.meta:type_name -> user.v1.MenuMeta
	4, // 7: user.v1.Menu.children:type_name -> user.v1.Menu
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_user_v1_model_proto_init() }
func file_user_v1_model_proto_init() {
	if File_user_v1_model_proto != nil {
		return
	}
	file_user_v1_model_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_model_proto_rawDesc), len(file_user_v1_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_model_proto_goTypes,
		DependencyIndexes: file_user_v1_model_proto_depIdxs,
		EnumInfos:         file_user_v1_model_proto_enumTypes,
		MessageInfos:      file_user_v1_model_proto_msgTypes,
	}.Build()
	File_user_v1_model_proto = out.File
	file_user_v1_model_proto_goTypes = nil
	file_user_v1_model_proto_depIdxs = nil
}
