// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/serviceaccount/v1/model.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceAccount is one machine's identity: CI, a job, another service.
//
// Authentication is still Keycloak's - a service account is a Keycloak client
// and a machine gets a token through the client credentials grant. This is the
// register that says the client exists, what it is for and who set it up.
type ServiceAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The hub user the machine acts as. It is a row in `users` like any other,
	// which is what lets a machine join groups, hold roles and appear in the
	// audit log through the same machinery a person does.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// What the machine is for. A machine nobody can describe is a machine nobody
	// dares turn off.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// What an operator puts in HUB_OIDC_CLIENT_ID. Derived from the name, so two
	// service accounts cannot claim the same client.
	ClientId        string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CreatedByUserId string                 `protobuf:"bytes,6,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceAccount) Reset() {
	*x = ServiceAccount{}
	mi := &file_system_serviceaccount_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccount) ProtoMessage() {}

func (x *ServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_system_serviceaccount_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccount.ProtoReflect.Descriptor instead.
func (*ServiceAccount) Descriptor() ([]byte, []int) {
	return file_system_serviceaccount_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceAccount) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ServiceAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceAccount) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ServiceAccount) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

func (x *ServiceAccount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServiceAccount) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Credentials are what a machine needs to authenticate.
//
// The secret is returned once, when it is issued, and never again: hub does not
// store it and Keycloak cannot always show it back. Losing it means rotating
// it, which is the right cost for a credential.
type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_system_serviceaccount_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_system_serviceaccount_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_system_serviceaccount_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *Credentials) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Credentials) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_system_serviceaccount_v1_model_proto protoreflect.FileDescriptor

const file_system_serviceaccount_v1_model_proto_rawDesc = "" +
	"\n" +
	"$system/serviceaccount/v1/model.proto\x12\x18system.serviceaccount.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\x0eServiceAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12+\n" +
	"\x12created_by_user_id\x18\x06 \x01(\tR\x0fcreatedByUserId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"B\n" +
	"\vCredentials\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secretB>Z<github.com/linzhengen/hub/server/pb/system/serviceaccount/v1b\x06proto3"

var (
	file_system_serviceaccount_v1_model_proto_rawDescOnce sync.Once
	file_system_serviceaccount_v1_model_proto_rawDescData []byte
)

func file_system_serviceaccount_v1_model_proto_rawDescGZIP() []byte {
	file_system_serviceaccount_v1_model_proto_rawDescOnce.Do(func() {
		file_system_serviceaccount_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_serviceaccount_v1_model_proto_rawDesc), len(file_system_serviceaccount_v1_model_proto_rawDesc)))
	})
	return file_system_serviceaccount_v1_model_proto_rawDescData
}

var file_system_serviceaccount_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_system_serviceaccount_v1_model_proto_goTypes = []any{
	(*ServiceAccount)(nil),        // 0: system.serviceaccount.v1.ServiceAccount
	(*Credentials)(nil),           // 1: system.serviceaccount.v1.Credentials
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_system_serviceaccount_v1_model_proto_depIdxs = []int32{
	2, // 0: system.serviceaccount.v1.ServiceAccount.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: system.serviceaccount.v1.ServiceAccount.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_system_serviceaccount_v1_model_proto_init() }
func file_system_serviceaccount_v1_model_proto_init() {
	if File_system_serviceaccount_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_serviceaccount_v1_model_proto_rawDesc), len(file_system_serviceaccount_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_serviceaccount_v1_model_proto_goTypes,
		DependencyIndexes: file_system_serviceaccount_v1_model_proto_depIdxs,
		MessageInfos:      file_system_serviceaccount_v1_model_proto_msgTypes,
	}.Build()
	File_system_serviceaccount_v1_model_proto = out.File
	file_system_serviceaccount_v1_model_proto_goTypes = nil
	file_system_serviceaccount_v1_model_proto_depIdxs = nil
}
